Logs RP deployment mode during startup
Azure/ARO-RP pull request #1088
Opened 2020-10-20 22:24 UTC by ihcsim

### What this PR does / why we need it:

Logs the RP deployment mode during startup.

The log output ensures developers are aware of the deployment mode that
their RP is running in.

### Test plan for issue:

Executes the `go run ./cmd/aro rp` command locally, with different `RP_MODE`
values:
```sh
# dev mode
RP_MODE="development" go run ./cmd/aro rp                                         
INFO[2020-10-20T15:19:59-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:19:59-07:00]pkg/env/core.go:52 env.NewCore() running in development mode

# int mode
RP_MODE="int" go run ./cmd/aro rp                                           
INFO[2020-10-20T15:20:45-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:20:45-07:00]pkg/env/core.go:52 env.NewCore() running in int mode

# prod mode
RP_MODE="production" go run ./cmd/aro rp                                 
INFO[2020-10-20T15:21:19-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:21:19-07:00]pkg/env/core.go:52 env.NewCore() running in production mode

# default
RP_MODE="" go run ./cmd/aro rp                                                
INFO[2020-10-20T15:21:45-07:00]cmd/aro/main.go:45 main.main() starting, git commit unknown
INFO[2020-10-20T15:21:45-07:00]pkg/env/core.go:52 env.NewCore() running in production mode
```

### Is there any documentation that needs to be updated for this PR?

Minor code change with no doc updates required.

2020-10-21 00:22 UTC, jim-minter requested changes

2020-10-21 00:22 UTC, jim-minter commented on pkg/env/core.go
>  	deploymentMode := deployment.NewMode()
there's another one of these in cmd/aro/operator.go which you might as well get too

2020-10-21 00:22 UTC, jim-minter commented on pkg/util/deployment/deployment.go
> +		fallthrough
hmm, we use "" == production (we default to production mode); from my perspective this change just confuses / is unnecessary extra text

2020-10-21 00:22 UTC, jim-minter commented on pkg/util/deployment/deployment.go
> +		fallthrough
ditto here

2020-10-22 10:25 UTC, mjudeikis commented
@ihcsim squash and lets merge

2020-10-22 16:07 UTC, ihcsim commented
/azp run ci

2020-10-22 16:08 UTC, mjudeikis commented
/azp run ci

2020-10-22 16:36 UTC, mjudeikis commented
/azp run e2e

2020-10-22 16:37 UTC, mjudeikis approved these changes

2020-10-23 01:06 UTC, jim-minter approved these changes

2020-10-23 01:07 UTC, merged

2020-10-23 01:07 UTC, jim-minter commented
> /azp run ci

@ihcsim you'll be able to do that once you have an account in the Azure org :-)