Remove vsts artifacts
Azure/ARO-RP pull request #1141
Opened 2020-11-10 22:05 UTC by jim-minter

* stop using vsts build artifacts and use docker images instead
* use the ARO-RP git commit instead of having to supply a vsoDeployerBuildID
* use the config git commit instead of having to supply a vsoConfigBuildID
* always docker logout when done with docker to avoid leaking credentials

2020-11-10 22:05 UTC, jim-minter commented
Untested.  @mjudeikis @Makdaam I wonder whether something like this will help us.  @hawkowl your view here would also be appreciated.

2020-11-24 01:53 UTC, jim-minter commented
@hawkowl @mjudeikis repushed.  Still untested.  Still would like a second look.

2020-11-24 09:07 UTC, mjudeikis commented
@jim-minter I think im fine with progressing with this, but before we start investing time, do you know if artifacts are involved in any way in Component governance scans? If they are not and we relay on cgmanifest - we can progress

2020-11-24 14:27 UTC, jim-minter commented
> artifacts are involved in any way in Component governance scans

To my knowledge, they are not.

2021-01-14 13:20 UTC, mjudeikis commented on .pipelines/templates/template-job-deploy-azure-env.yml
> +              git://AzureRedHatOpenShift/RP-Config@${{ parameters.rpConfigCommit }}
This does not work with:
![image](https://user-images.githubusercontent.com/3225744/104595968-3a07a100-566b-11eb-9542-0da82db97420.png)
 
There is some issues how VSTS handles checkouts with inline syntax and commit hash'es

2021-01-14 13:22 UTC, mjudeikis commented on .pipelines/templates/template-job-deploy-azure-env.yml
> +              git://AzureRedHatOpenShift/RP-Config@${{ parameters.rpConfigCommit }}
I have a feeling it does it via ref not commit resolution ;/

2021-01-14 13:26 UTC, mjudeikis requested changes
@jim-minter let's discuss this. I think VSTS is a bit limited in what we can do ;/

2021-02-08 17:13 UTC, jim-minter commented
Abandoning this for now - revisit as part of ev2 work

2021-02-08 17:13 UTC, closed without merging