Fix payload panic
Azure/ARO-RP pull request #1272
Opened 2021-01-25 12:50 UTC by mjudeikis

### Which issue this PR addresses:

Fixes panic when empty body is passed directly to the api.

### What this PR does / why we need it:

Currently if you pass no body instead of `{}` assertion fails due to `var ext interface{}`

2021-01-25 14:17 UTC, mjudeikis commented
I dont think this is quote right yet. Need to think more once oncall is done

2021-01-25 18:29 UTC, mjudeikis commented
/azp run e2e

2021-01-27 23:48 UTC, jim-minter requested changes
I don't understand how to recreate the bug, and I don't understand why the fix is in the static validator and not in openshiftcluster_putorpatch.go.

2021-02-09 13:18 UTC, mjudeikis commented
I know this happens in geneva actions. But I think im not bothered enough at this point

2021-02-09 13:18 UTC, closed without merging