Add dependency update documentation
Azure/ARO-RP pull request #1378
Opened 2021-03-10 15:08 UTC by petrkotas

### What this PR does / why we need it:

Add vendorind and dependency update documentation with
vendoring process of ARO-RP.

Signed-off-by: Petr Kotas <pkotas@redhat.com>

### Test plan for issue:

None, doc update.

### Is there any documentation that needs to be updated for this PR?

It is documentation itself.

2021-03-11 08:44 UTC, mjudeikis commented on docs/updating-dependencies.md
> +# Updating dependencies aka vendoring
Match header with fine name 
```
# Updating dependencies
```

2021-03-11 15:44 UTC, jim-minter requested changes
+1 with changes - thanks @petrkotas

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +To update golang dependencies one have to choose between two options:
```suggestion
To update golang dependencies one has to choose between two options:
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +is that packages modified in this script does not fully support modules and
```suggestion
is that packages modified in this script do not fully support modules and
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +semantic versioning via tags. Therefore the proper version parsed from the version
```suggestion
semantic versioning via tags. Therefore the proper version is parsed from the version
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +When upgrading to never version of OpenShift, this script have to be updated to
```suggestion
When upgrading to a newer version of OpenShift, this script has to be updated to
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +When adding new dependencies or updating old ones, based by the requirement of
```suggestion
When adding new dependencies or updating old ones, based on the requirement of
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +the the PR, one can simply call
```suggestion
the PR, one can simply call
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +go get -u <module to be updated>
mention the `go get -u <module>@<release>` syntax here?

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +and due to problematic OpenShift packages.
```suggestion
make vendor is required as ARO mirrors all dependencies locally for CI reliability and reproducability.
```

2021-03-11 15:44 UTC, jim-minter commented on docs/updating-dependencies.md
> +**NOTE** when updating the package modified in `hack/update-go-module-dependencies.sh`
```suggestion
**NOTE** when updating a package modified in `hack/update-go-module-dependencies.sh`
```

2021-03-12 11:17 UTC, petrkotas commented
Thank you both for the checks.

2021-03-15 11:09 UTC, petrkotas commented
/azp run e2e

2021-03-15 15:03 UTC, mjudeikis approved these changes

2021-03-15 15:04 UTC, merged