Change UUID module to address WS-2018-0594
Azure/ARO-RP pull request #1408
Opened 2021-03-22 21:32 UTC by jewzaam

### Which issue this PR addresses:

Fixes https://www.whitesourcesoftware.com/vulnerability-database/WS-2018-0594

### What this PR does / why we need it:

Move from github.com/satori/go.uuid to github.com/gofrs/uuid for uuid generation.  Requires additional tweaks.
Dependency azure-sdk-for-go needed updated, it is moved to latest release.
Signature of NewV4() changed to return multiple values.  Created facade in pkg/util/uuid to allow us to continue using in-line with single argument returned.

### Test plan for issue:

Existing unit and integration tests.

### Is there any documentation that needs to be updated for this PR?

No, internal dependency update.

2021-03-22 21:59 UTC, jim-minter requested changes

2021-03-22 21:59 UTC, jim-minter commented on pkg/util/uuid/uuid.go
> +	u, _ := uuid.NewV4()
must read the error and panic if it is set; not to do so here could be a security risk

2021-03-22 21:59 UTC, jim-minter commented on pkg/util/uuid/uuid.go
> +}
please set your editor to add trailing newlines to files

2021-03-22 21:59 UTC, jim-minter commented on hack/validate-imports/validate-imports.go
>  		case "github.com/google/uuid":
```suggestion
		case "github.com/google/uuid", "github.com/satori/go.uuid":
```

2021-03-22 21:59 UTC, jim-minter commented on hack/validate-imports/validate-imports.go
>  		return []string{"uuid"}
remove these lines

2021-03-22 21:59 UTC, jim-minter commented on pkg/util/uuid/uuid.go
> +// This is a facade to aid in conversion from github.com/satori/go.uuid to github.com/gofrs/uuid
+1 on using a facade

2021-03-23 07:34 UTC, mjudeikis commented on pkg/util/uuid/uuid.go
> +
You are missing Microsoft license here. Run all tests locally for it to be generated or just add it from other files.

2021-03-24 21:08 UTC, jewzaam commented
/azp run E2E

2021-03-25 10:55 UTC, gvanderpotte commented
/azp run e2e

2021-03-26 13:52 UTC, jewzaam commented
/hold

cloud-credential-operator dependency relies on github.com/satori/go.uuid so it's still being referenced in go.sum

2021-03-31 18:29 UTC, jim-minter commented
merging; given that actually uuid.Must() exists let's follow up and remove pkg/util/uuid and standardise further.

2021-03-31 18:29 UTC, merged