add InfraID to admin API
Azure/ARO-RP pull request #1560
Opened 2021-06-23 13:18 UTC by rolandmkunkel

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2021-06-23 16:22 UTC, bennerv requested changes

2021-06-24 14:22 UTC, rolandmkunkel commented
/azp run ci

2021-06-24 14:35 UTC, nilsanderselde commented
/azp run ci

2021-06-24 14:35 UTC, nilsanderselde commented
/azp run e2e

2021-06-25 09:58 UTC, m1kola requested changes

2021-06-25 09:58 UTC, m1kola commented on pkg/api/admin/openshiftcluster_convert.go
> +			InfraID:       oc.Properties.InfraID,
I think we also need it in `ToInternal`.

2021-06-25 09:58 UTC, m1kola commented on test/e2e/adminapi_cluster_get.go
> +		Expect(oc.Properties.InfraID).ToNot(BeEmpty())
I think it should not be empty: all new clusters should have it. Also once we run and upgrade with https://github.com/Azure/ARO-RP/pull/1536 (yet to happen) the old clusters will have it too.

2021-06-25 11:30 UTC, m1kola commented on test/e2e/adminapi_cluster_get.go
> +		Expect(oc.Properties.InfraID).ToNot(BeEmpty())
Disregard this. I misread the test. It says “To not be empty”. I read it as “to be empty”.

2021-06-25 12:55 UTC, m1kola approved these changes

2021-06-25 12:57 UTC, m1kola commented
/azp run e2e

2021-06-28 13:39 UTC, mjudeikis commented
/azp run ci

2021-06-28 14:18 UTC, merged