update keyvault api version to 2019-09-01
Azure/ARO-RP pull request #1683
Opened 2021-08-17 11:58 UTC by rolandmkunkel

### Which issue this PR addresses:
Updates the keyvault API version to 2019-09-01

Fixes

### What this PR does / why we need it:

The newer API version contains models for key, which allows us to create keys through templates.

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

no

2021-08-18 16:34 UTC, m1kola commented on go.mod
> +	github.com/azure/azure-sdk-for-go v56.2.0+incompatible // indirect
It semes like conflicts were resolved incorrectly. Try to run `go mod tidy` and `go mod vendor`: it removes changes from `go.mod`, `go.sum` and `vendor/modules.tx`.

2021-08-18 17:12 UTC, m1kola commented
@rolandmkunkel I see the updated version of the PR. What version of Go you use? When I ran these commands with 1.14.15 against the previous version of the PR it only removed `github.com/azure/azure-sdk-for-go` related stuff from `go.sum`.

2021-08-18 18:56 UTC, troy0820 requested changes
nit: I tend to make any changing of dependencies `vendor` a separate commit.  This will help with what @m1kola is seeing as well.  I did a go mod vendor and it added everything back that was deleted in `go.sum` and I'm using go 1.15.14.  

Then I would make the second commit the make generate/changing the apiversions in `pkg/util/azureclient/apiversions.go`
- [ ] Make dependencies vendor a separate commit
- [ ] Create commit with changes to `apiversions.go` and `make generate`

2021-08-19 10:56 UTC, rolandmkunkel commented
I didn't have to update my SDK, so all is in one commit now

2021-08-19 11:49 UTC, m1kola approved these changes

2021-08-19 13:00 UTC, troy0820 approved these changes

2021-08-19 13:55 UTC, merged