Certificate issue adjust
Azure/ARO-RP pull request #1687
Opened 2021-08-18 10:01 UTC by mjudeikis

### Which issue this PR addresses:

Fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10631458

### What this PR does / why we need it:

Customer sometimes deletes secrets which we populate from the key-vaults[1]. If those secrets are gone we can't restore them with [2] because of [3].

We should be doing this:

Make Conditional wait best effort where we can. In this case scenario API server is partially alive but our condition fails as Operator is not happy. In those cases actions timeouts, attempts to try other steps and should work. Worst case we will fail down the chain...
We should move certificate configuration higher in the AdminUpdate order to avoid somebody else tripping us.
We should have a backup secret copy in ARO operator namespace just for cases when 1-2 fails. 

https://github.com/Azure/ARO-RP/blob/master/pkg/cluster/tls.go#L72
https://github.com/Azure/ARO-RP/blob/master/pkg/cluster/install.go#L51-L52
https://github.com/Azure/ARO-RP/blob/master/pkg/cluster/install.go#L38

### Test plan for issue:

Unti tests adjusted

### Is there any documentation that needs to be updated for this PR?

No

2021-08-18 14:07 UTC, petrkotas requested changes
Hi @mjudeikis, good one fixing it. I like the simplistic approach. Pardon my nitpicking, would you look at my comment please?

2021-08-18 14:07 UTC, petrkotas commented on pkg/util/steps/condition.go
> +func Condition(f conditionFunction, timeout time.Duration, fail bool) conditionStep {
The behavior of `Condition` changed with addition of `fail` parameter, which can be seen to have different meanings. How easy would the function be with updated documentation header with the right meaning?

2021-08-20 12:29 UTC, mjudeikis commented
Open question here if we should extend existing step def as done now, or create new one `ConditionBestEffort` ?

2021-08-20 15:06 UTC, jewzaam approved these changes
To be clear on the intent of this work, it's to ensure we don't fail deploy on apiserver so we have a chance to fix in later steps.  The copy of the secrets in the openshift-azure-operator namespace is for case that getting the secret from vault fails and SRE has a backup option to copy the secret to openshift-config.

I'd argue that ARO operator could use this but I think it would rely on keyvault only and if we need the backup things are very very bad with the cluster.  Not coming up with the use case when the backup is usable, if the cluster is in such a bad state, but I have nothing against such backup.

2021-08-20 18:16 UTC, merged

2021-08-30 09:31 UTC, mjudeikis commented on pkg/cluster/tls.go
> +		}
Yes, we are saving it in 2 places now on the cluster. There were multiple occasions we needed it ;/