Auto-capacity-allocation
Azure/ARO-RP pull request #1787
Opened 2021-10-12 15:03 UTC by petrkotas

### Which issue this PR addresses:

Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/9673960/

### What this PR does / why we need it:

Introduce new feature flag to enable AutoSizedNodes. This enables the openshift feature to compute
resource allocation dynamically based on the node size. It does that by creating Kubeletconfig config with the feature turned on.

It also removes the aro-limits KubeletConfig that will be conflicting.

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2021-11-25 17:25 UTC, m1kola requested changes
Question: when we create/delete these `KubeletConfig` with `AutoSizingReserved`  - what happens? Will it rotate the node/restart kubelet?

2021-11-25 17:25 UTC, m1kola commented on pkg/operator/controllers/configs/config_autonodesize.go
> +	return builder.Owns(&mcv1.KubeletConfig{})
Should we add a predicate to make sure that we only reconcile `configName` and don't care about rest of the `KubeletConfig` objects?

This also removes the need to do this all the time:

```go
key := types.NamespacedName{
	Name: configName,
}
```

We shoud be able to just use `ctrl.Request` which we receive in `Reconcile`.

2021-11-25 17:25 UTC, m1kola commented on pkg/operator/controllers/configs/config_autonodesize.go
> +	if aro.Spec.Features.ReconcileAutoSizedNodes {
It is `false` by default. Do we want to update `pkg/operator/deploy/deploy.go` to enable it?

2021-11-25 17:25 UTC, m1kola commented on pkg/operator/controllers/configs/doc.go
> +// Other related objects are added in individual configs.
I'm not convinced that we should implement a generic config controller at this point.

I would probably start with a controller which does one thing: reconciles one specific kubeletconfig. If/when we see more use cases for this we can reconsider having a generic controller for configs.

2021-12-01 10:13 UTC, petrkotas commented
I experienced multiple issues when reworking the PR, closing in favor of https://github.com/Azure/ARO-RP/pull/1862 which reworks the item mentions in this PR.

2021-12-01 10:13 UTC, closed without merging