Geneva region quota
Azure/ARO-RP pull request #1839
Opened 2021-11-15 19:04 UTC by jhoreman

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

This PR supports the ListVMResize Geneva action work on the ARO RP side. 

### Test plan for issue:

<!--
How did you test that this PR works?

We can manually test the functionality of this geneva action call through a local mock geneva actions environment.

### Is there any documentation that needs to be updated for this PR?

Yes, will be written as an SOP for SRE use.

2021-11-16 21:47 UTC, jhoreman commented
/azp run ci

2021-11-19 18:21 UTC, bennerv submitted a review, later dismissed
Just mostly naming nits to be more clear about what's happening.  Take it how you wish.  

ResizeOptions rather than Sizes becasue sizes implies sizes for a region, not valid resize options for a VM.

2021-11-19 23:54 UTC, jhoreman commented on pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
> +	return future.Value, err
Agreed, handled.

2021-11-19 23:54 UTC, jhoreman commented on pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
> +	ListVMSizes(ctx context.Context, resourceGroupName string, VMName string) (result *[]mgmtcompute.VirtualMachineSize, err error)
Agreed, handled.

2021-11-22 17:58 UTC, bennerv commented on pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
> +	return future.Value, err
looks like it's still using `future.Value`

2021-11-22 19:26 UTC, jhoreman commented on pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
> +	return future.Value, err
Made update but missed commit, should be good now.

2021-12-21 02:52 UTC, hawkowl requested changes
Not sure about the test content -- it seems unrelated to what the Azure API returns?

2021-12-21 02:52 UTC, hawkowl commented on pkg/frontend/admin_openshiftcluster_vmsizelist_test.go
> +				a.EXPECT().
This test content seems unrelated?

2022-01-11 23:27 UTC, jhoreman commented
Discovered this call does not properly evaluate subscription level usage limits, only region specific limits. Will re-write to look at usage limits based on subscription id + location.

2022-01-12 18:04 UTC, cadenmarchese commented on pkg/frontend/admin_openshiftcluster_vmsizelist.go
> +	a, err := f.azureActionsFactory(log, f.env, doc.OpenShiftCluster, subscriptionDoc)
I'm not sure if this helps with all subscription-specific concerns here, but https://github.com/Azure/ARO-RP/pull/1790 has logic that checks subscription-specific VM availability at install time by using Azure's mgmt compute API (https://github.com/Azure/ARO-RP/pull/1790/files#diff-0bb64ff9a5edb73627cfdbda167ba828c955c1441d9d3eb723c6e06696f1b266R19-R23) using the spAuthorizer.

Do you think it makes sense to move the logic in https://github.com/Azure/ARO-RP/pull/1790 to `pkg/util/computeskus` where we can use it in both places?

2022-02-11 22:31 UTC, closed without merging