Replace old `github.com/gogo/protobuf` versions
Azure/ARO-RP pull request #1867
Opened 2021-12-03 17:16 UTC by cadenmarchese

### Which issue this PR addresses:

Partially fixes https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/12715854/.

### What this PR does / why we need it:

Our codebase has a transient dependency on `github.com/gogo/protobuf`:
```
$ go mod why -m github.com/gogo/protobuf
github.com/Azure/ARO-RP/hack/gendiscoverycache
```
The older versions of github.com/gogo/protobuf currently imported in ./go.sum are affected by CVE https://access.redhat.com/security/cve/cve-2021-3121. This PR replaces all older versions in ./go.sum with the fixed version.

### Test plan for issue:

Ran `make test-go`, `e2e`, `go mod vendor`, `go mod tidy`, etc..

### Is there any documentation that needs to be updated for this PR?

No

2021-12-03 18:43 UTC, jewzaam requested changes
Looks like manual removal of stuff from go.sum.  Run `go mod tidy` and at least v1.3.1 comes back.  Use the exclude portion of `go.mod`.  From the ADO you'll need to add this at a minimum:

```
    github.com/golang/protobuf v1.0.0
    github.com/golang/protobuf v1.1.1
    github.com/golang/protobuf v1.2.0
    github.com/golang/protobuf v1.2.1
    github.com/golang/protobuf v1.3.0
    github.com/golang/protobuf v1.3.1
```

2021-12-06 15:03 UTC, cadenmarchese commented
@jewzaam I added the affected packages to go.mod `exclude` - do we still need `github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2` in the `replace`?

2021-12-21 02:32 UTC, hawkowl commented
We also depend on a fixed version of the Kubernetes components, so this should be fine to make the dependency checker happy.

2021-12-21 02:33 UTC, hawkowl approved these changes

2021-12-21 02:33 UTC, merged