Make createOrUpdateRouterIPFromCluster reuse existing code + extra case for TestAroDeploymentReady
Azure/ARO-RP pull request #2008
Opened 2022-03-16 14:15 UTC by m1kola

### What this PR does / why we need it:

Just a follow up for #1972:

* Makes `createOrUpdateRouterIPFromCluster` reuse `isIngressProfileAvailable`
* And after merge I noticed that we should probably add an extra test case into `TestAroDeploymentReady`.

### Test plan for issue:

Unit tests should cover the changes

### Is there any documentation that needs to be updated for this PR?

No, just refactoring

2022-03-23 09:38 UTC, m1kola commented
/azp run e2e

2022-03-28 22:32 UTC, bennerv submitted a review, later dismissed

2022-03-29 13:07 UTC, s-amann requested changes
lgtm, can we remove or clean up the comment?

2022-03-29 13:07 UTC, s-amann commented on pkg/cluster/ipaddresses.go
>  	// in both cases we can't do much so return early. Ingress profile can
Can we remove or clean up this comment now that we are using a well named function I think it explains itself.

2022-04-12 10:38 UTC, m1kola commented
@bennerv @s-amann I cleaned up the comment. Could you please take another look?

2022-04-12 11:34 UTC, bennerv approved these changes
LGTM. 

We rely heavily on this ingress IP address due to the integrations with the dnsmasq controller.  If for some reason the ingress IP address will not populate within the cluster doc, we're going to have issues deploying the operator, DNS for the *.apps domain may go sideways (if the ingress service was deleted or recreated with a new IP address).

2022-04-13 10:30 UTC, merged