modified pipeline doc folder exclude rule
Azure/ARO-RP pull request #2014
Opened 2022-03-18 12:07 UTC by bizz001

### Which issue this PR addresses:

Fixes CI not ignoring commits containing only doc changes.

### What this PR does / why we need it:

Prevents CI from running on doc only commits.

2022-03-18 13:29 UTC, petrkotas approved these changes
LGTM nice catch

2022-03-18 18:48 UTC, bryanro92 requested changes
I'm not sure why - but this isn't working. CI is still running, and the pipelines run off your PR branch. I tested a similar change for e2e testing.

Could you implement what I did here for `e2e.yml`? https://github.com/bryanro92/ARO-RP/commit/d99a7a15aedacda3602d6f23d0c2b0c8d30c0bc0

I copied exact pattern from ci.yml to e2e.yml and it circumvented e2e from running, but CI is still running :thinking: 

EDIT: CI actually blew up on my suggested changes with
```
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in ".pipelines/e2e.yml", line 2, column 8
```
However, if we get CI to exclude properly then it wont fail :smile:

2022-03-22 10:28 UTC, m1kola commented on .pipelines/ci.yml
> +    - docs/
It should probably be a recursive wildcard instead: `**`. Found some docs on it:

* https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-192-update#support-for-wild-cards-in-path-filters
* https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml
* https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

2022-08-15 12:16 UTC, m1kola commented
@bizz001 is it something we still need? If so, could you please rebase and make sure that CI is green?

2022-10-31 12:41 UTC, cadenmarchese commented
@bizz001 bump to address comments above (if we still need this PR).

2023-01-03 08:50 UTC, closed without merging