WIP: Cfs/rh cf rp dev env working sessions
Azure/ARO-RP pull request #2017
Opened 2022-03-18 19:45 UTC by coreyperkins

Work-in-progress: Do not merge. Using to track working sessions between RH and my org.

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2022-03-25 02:10 UTC, bryanro92 approved these changes

2022-03-25 02:18 UTC, bryanro92 commented on Makefile
>  		sed -i -e "s|^dev_sources = $(PWD)$$|dev_sources = $(PWD)/python|" ~/.azure/config
sorry for the noise - needed a pr w/o any comments/reviews and am testing something

2022-03-25 02:18 UTC, bryanro92 commented on Makefile
>  		sed -i -e "s|^dev_sources = $(PWD)$$|dev_sources = $(PWD)/python|" ~/.azure/config
2

2022-03-25 02:18 UTC, bryanro92 commented on Makefile
3

2022-03-25 02:23 UTC, bryanro92 requested changes
sorry for noise... testing a feature

2022-05-03 13:58 UTC, coreyperkins commented
Closing this PR, it was only used for experimentation purposes.

2022-05-03 13:58 UTC, closed without merging