[HOLD] Cluster create after api 2022-04-01
Azure/ARO-RP pull request #2035
Opened 2022-04-01 19:36 UTC by 25region

### Which issue this PR addresses:

Cluster creation process after the API release

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2022-04-06 18:58 UTC, bennerv submitted a review, later dismissed
This will pass in PR e2e because it runs a local RP and doesn't talk to upstream.  It won't pass in an INT deploy on master because the ARM manifest has yet to be updated and deployed hence the hold label.

2022-04-12 13:15 UTC, s-amann approved these changes
lgtm

2022-05-03 18:44 UTC, bennerv commented
@25region can you rebase and we can merge this?

2022-05-03 19:24 UTC, bennerv requested changes
One change we didn't catch before.

2022-05-03 19:24 UTC, bennerv commented on pkg/util/cluster/cluster.go
> +		oc.Properties.ClusterProfile.FipsValidatedModules = api.FipsValidatedModulesDisabled
This should be removed.  We can create FIPs clusters anywhere.  

Also, can you set FIPs to enabled by default?  It should be in the api doc above on line 403

2022-05-03 21:20 UTC, bennerv requested changes
just one final change and LGTM

2022-05-03 21:20 UTC, bennerv commented on pkg/util/cluster/cluster.go
> +				FipsValidatedModules: "Enabled",
nit  for consistency.  Should be the last one.  
```suggestion
				FipsValidatedModules: api.FipsValidatedModulesEnabled,
```

2022-05-04 15:24 UTC, bennerv approved these changes
lgtm

2022-05-04 15:24 UTC, merged