Dropping ipRules parameter; it is not used in this template (causes "unable to parse template on line 1" error)
Azure/ARO-RP pull request #2075
Opened 2022-04-21 14:17 UTC by coreyperkins

It is worth noting that it is used in the rp-production.json template but leaving it in place in the rp-development.json template unused results in a syntax error that states "unable to parse template on line 1". This causes the process to hang when settings up role assignments for the shared rp.

### Which issue this PR addresses:

https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14203980/

### What this PR does / why we need it:

Allows us to setup the shared RP.

### Test plan for issue:

This has been tested by multiple parties via shared RP setup.

### Is there any documentation that needs to be updated for this PR?

Documentation for this and other issues related to setting up the shared RP env and running the RP process locally is coming in another PR.

2022-04-21 14:17 UTC, coreyperkins commented
@karanmagdani

2022-04-21 17:35 UTC, karanmagdani submitted a review, later dismissed
LGTM

2022-04-22 10:28 UTC, m1kola requested changes
Same as [here](https://github.com/Azure/ARO-RP/pull/2067#pullrequestreview-949852577): I did not look into why we need this, but `deploy/rp-development.json` is generated and `make generate` will override manual changes.

https://github.com/Azure/ARO-RP/blob/5668a316afae97b690871edac2c59eb8f84efacb/pkg/deploy/generator/templates_rp.go#L21-L151

2022-05-02 16:37 UTC, bennerv commented
@coreyperkins mind updating the `pkg/deploy/generator/templates_rp.go` and removing all instances of this.  Then a `make generate` should resolve everything here and we can merge.

2022-05-03 14:18 UTC, coreyperkins commented
@bennerv @m1kola -- thanks for the tips!

Ben, I did not remove all instances because I noticed when I ran `make generate` the deploy/rp-production.json still had references to ipRules on line 720: 

`"ipRules": "[if(parameters('disableCosmosDBFirewall'), createArray(), concat(parameters('ipRules'),createArray(createObject('ipAddressOrRange', '104.42.195.92'),createObject('ipAddressOrRange','40.76.54.131'),createObject('ipAddressOrRange','52.176.6.30'),createObject('ipAddressOrRange','52.169.50.45'),createObject('ipAddressOrRange','52.187.184.26'))))]",`

I did, however, move the `ipRules` parameter in `pkg/generator/templates_rp.go` to the array of params that gets appended if the g.production check succeeds on line 30.

Is this correct? If not, how should I proceed? Thanks!

2022-05-03 19:28 UTC, bennerv commented
@coreyperkins this needs a `make generate`.  

On a side note, do you know what the `ipRules` parameter gets parameterized into when it fails?  Is it an empty array, or something else?  If it's an empty array, it should still work so I'm a bit confused on why it's failing as the logic within the ARM template should be sufficient that it works for dev and prod without _special_ modification.

2022-05-04 15:09 UTC, coreyperkins commented
@bennerv Hi Ben! I am going to reach out to you direct this morning for guidance and then I will document here what we discuss. Thanks!

2022-05-04 17:46 UTC, coreyperkins commented
Per @bennerv request I ran `make generate` and submitted the `pkg/deploy/bindata.go` file. Also, we were running into the error because ipRules had no default value (and was thus required). As a reference we were running the command from the shell helper file (https://github.com/Azure/ARO-RP/blob/master/hack/devtools/deploy-shared-env.sh) per the instructions at https://github.com/Azure/ARO-RP/blob/master/docs/prepare-a-shared-rp-development-environment.md. With ipRules now gone this is no longer presenting the error. Thanks!

2022-05-04 19:26 UTC, bennerv approved these changes
lgtm - shouldn't need to use ipRules in dev anyway.

2022-06-28 17:50 UTC, coreyperkins commented
@bennerv @m1kola -- I believe we are good here now, but if not please advise!

2022-07-07 01:52 UTC, ross-bryan approved these changes

2022-08-09 01:40 UTC, hawkowl approved these changes

2022-08-09 01:40 UTC, merged