add minor version
Azure/ARO-RP pull request #2091
Opened 2022-04-27 11:18 UTC by gvanderpotte

### Which issue this PR addresses:

We need a quick and live way to check the list of OCP minor versions along with the resourceID and subscriptionID to easily identify out of support lifecycle clusters. Due to Geneva limitations, we need to provide the minor version along with the full version to be able to generate corresponding report on Geneva side. 

### What this PR does / why we need it:

We need a quick and live way to check the list of OCP minor versions along with the resourceID and subscriptionID to easily identify out of support lifecycle clusters. Due to Geneva limitations, we need to provide the minor version along with the full version to be able to generate corresponding report on Geneva side. 

### Test plan for issue:

- Are there unit tests? yes
- Are there integration/e2e tests? no

### Is there any documentation that needs to be updated for this PR?

2022-04-27 11:26 UTC, m1kola commented on pkg/monitor/cluster/clusterversions.go
> +	}
I think version can be `4.3.0-0.nightly-2020-04-17-062811` where last `.` is part of suffix.

You might want to use `version.ParseVersion(...)` instead.

2022-05-02 13:55 UTC, ross-bryan submitted a review, later dismissed
lgtm only concern is another column which our log aggregation seems to have trouble with

2022-05-03 08:08 UTC, gvanderpotte commented
> lgtm only concern is another column which our log aggregation seems to have trouble with

I think that log column aggregation and metric column aggregation are different processes, so we should be safe here. That said, this does not prevent us from doing cleaning of unused pre-aggregates

2022-05-03 11:40 UTC, gvanderpotte commented
Added push of latest GA version from RP perspective. It is not super optimal from pure monitor perspective, as this could be pushed as an RP metric (as it is the same for all clusters in a given region). That said, this would force us to make a join on Geneva side (between metrics from different accounts), while the goal here is to have an easy way to detect to detect out of support lifecycle clusters

2022-05-03 13:40 UTC, gvanderpotte commented
/azp run e2e

2022-05-06 11:39 UTC, m1kola requested changes

2022-05-06 11:39 UTC, m1kola commented on pkg/util/version/version.go
> +func (v *Version) GetMinorVersion() string {
```suggestion
func (v *Version) MinorVersion() string {
```

As per https://go.dev/doc/effective_go#Getters

2022-05-06 11:39 UTC, m1kola commented on pkg/monitor/cluster/clusterversions.go
> +		actualMinorVersion = fmt.Sprintf("%d.%d", parsedVersion.V[0], parsedVersion.V[1])
Why not `parsedVersion.MinorVersion()`?

2022-05-06 11:39 UTC, m1kola commented on pkg/monitor/cluster/clusterversions.go
> +		"latestGaMinorVersion":                 version.InstallStream.Version.GetMinorVersion(), // Latest GA in ARO Minor version
I'm a bit puzzled by presence of `resourceProviderVersion` and `latestGaMinorVersion` here: this metric is related to cluster. But the above demensions are related RP. Why do we have them here?

2022-05-06 13:03 UTC, m1kola commented on pkg/monitor/cluster/clusterversions.go
> +		"latestGaMinorVersion":                 version.InstallStream.Version.GetMinorVersion(), // Latest GA in ARO Minor version
@gvanderpotte

> resourcePRoviderVersion is the version of the RP that has provisionned the cluster (last PUCM by).

No, `resourcePRoviderVersion` is a version of the RP which sends the metric. It is static `version.GitCommit` constant.

Last PUCM'ed by is `provisionedByResourceProviderVersion`

2022-05-06 13:06 UTC, m1kola approved these changes
Looks good to me, assuming that we cant not solve geneva limitation in some other way.

2022-05-10 11:50 UTC, merged