Add new ARO regions to pipelines
Azure/ARO-RP pull request #2139
Opened 2022-05-25 15:11 UTC by mbarnes

### Which issue this PR addresses:

Work items per region:
- [australiacentral](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14209523)
- [australiacentral2](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14209565)
- [swedencentral](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14216349)

### What this PR does / why we need it:

Part of the [new region rollout](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/59387/New-region-rollout?anchor=update-rp-pipelines) process.

### Test plan for issue:

N/A : This is a pipeline change.

### Is there any documentation that needs to be updated for this PR?

See process documentation and work items above.

2022-05-26 19:34 UTC, cadenmarchese approved these changes

2022-05-27 12:56 UTC, bennerv requested changes
Should be added to `prod-release-tag.yml` pipeline as well.  Please update the docs to include these as well.

2022-05-27 14:09 UTC, mbarnes commented
Thanks for catching that.  Fixed commit and [updated documentation](https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/59387/New-region-rollout?anchor=update-rp-pipelines).

2022-05-31 20:49 UTC, bennerv approved these changes
lgtm

2022-05-31 20:49 UTC, merged