Create DNS record for the AKS API during provisioning
Azure/ARO-RP pull request #2170
Opened 2022-06-10 07:25 UTC by darthhexx

### Which issue this PR addresses:

AKS generates a random FQDN for the cluster API and, although we can interrogate for it, we should have a common naming convention. 

### What this PR does / why we need it:

Provides a known URL pattern to access AKS in the shared dev environments, namely: api.aks.{australiaeast,eastus,westeurope}.osadev.cloud

### Test plan for issue:

The ARM template has already been deployed to the shared environments

### Is there any documentation that needs to be updated for this PR?

No.

2022-06-10 12:30 UTC, s-amann submitted a review, later dismissed
lgtm

2022-06-14 22:35 UTC, SudoBrendan submitted a review, later dismissed
LGTM

2022-06-27 09:44 UTC, facchettos requested changes
It would be great to get rid of bindata here and use embed instead

2022-07-18 01:48 UTC, darthhexx commented
@facchettos bindata is gone :smile:

2022-07-18 05:00 UTC, hawkowl approved these changes

2022-07-18 06:38 UTC, facchettos approved these changes

2022-07-18 06:47 UTC, merged