Store Live RP Settings in KeyVault
Azure/ARO-RP pull request #2283
Opened 2022-07-27 04:32 UTC by hawkowl

### Which issue this PR addresses:

Fixes https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/14625923

### What this PR does / why we need it:

Initial cut of storing RP config in a KeyVault that can be fetched or updated at runtime.

### Test plan for issue:

Unit tests, although no E2E yet

### Is there any documentation that needs to be updated for this PR?

N/A yet

2022-08-01 12:14 UTC, rolandmkunkel commented
How does the hive AKS kubeconfig get in the keyvault in the first place?

2022-08-01 12:46 UTC, bennerv requested changes

2022-08-01 12:46 UTC, bennerv commented on pkg/deploy/generator/resources_rp.go
> +			ObjectID: to.StringPtr("[parameters('fpServicePrincipalId')]"),
This should be the RP MSI, not the FP SP.  You're using the RP's MSI to setup a keyvault client above.

2022-08-03 04:10 UTC, ross-bryan requested changes
this looks like good start. a couple of comments/questions and to reiterate both ben/rolands comments regarding how are we uploading/pushing to these keyvaults? and to set the ACLs to RP MSI.

2022-08-03 04:10 UTC, ross-bryan commented on pkg/util/liveconfig/hive.go
> +	secret, err := p.kv.GetSecret(ctx, HiveKeyvaultSecret)
is there anyway we can verify we have all required config defined in the keyvault before we fail on grabbing individual components of the  "live config"?

2022-08-08 02:12 UTC, closed without merging