10581366-validate the current OCP version
Azure/ARO-RP pull request #2324
Opened 2022-08-12 09:00 UTC by LiniSusan

### Which issue this PR addresses:

https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/10581366
Fixes

### What this PR does / why we need it:

Created a new function: validateVersion in pkg/frontend/validate.go to fetch the list of installed version and compare whether current version is listed in it or not. Invoked this function in pkg/frontend/openshiftcluster_putorpatch.go
Also added new error constant: CloudErrorCodeInvalidVersion in pkg/api/error.go for version validation

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2022-08-15 20:28 UTC, ross-bryan requested changes
install version is not a URL parameter, it is in body of payload

2022-08-15 20:28 UTC, ross-bryan commented on pkg/frontend/openshiftcluster_putorpatch.go
> +	installVersion := vars["install-version"]
install version shouldn't be coming from vars, it should be in the body of the payload

2022-08-15 20:33 UTC, ross-bryan commented on pkg/frontend/openshiftcluster_putorpatch.go
> +		err := f.validateVersion(installVersion)
we should also validate during a PATCH request that the clusterProfile version is not modified

2022-08-23 11:49 UTC, anshulvermapatel commented
/azp run ci

2022-09-14 05:03 UTC, darthhexx commented
Closing this PR, because the functionality was added into #2374

2022-09-14 05:03 UTC, closed without merging