Refactor "pkg/deploy/generator": extract huge hardcoded strings
Azure/ARO-RP pull request #2378
Opened 2022-09-02 12:40 UTC by AldoFusterTurpin

### Which issue this PR addresses:

Fixes readability issues in the codebase regarding huge hardcoded strings in pkg/deploy/generator/*.go

### What this PR does / why we need it:

Having hardcoded strings with 580+ lines in the middle of a big Go function is something we should avoid as we lose focus on what the code was doing (the method becomes hard to follow and understand). 

This PR just extracts those hardcoded strings into a different file (scripts.go) and creates a function for each script. 

I have added some simple Unit Tests to ensure the returned strings are the same as the original ones. Ideally, in Unit Tests, you want to test behavior but not state, but due to the nature of the current solution we can only ensure that the given string is the expected one (at least is something). 

Refactor benefit: the inclusion of the unit tests has the advantage that now, someone familiar with those scripts, can extract the common parts (there are a lot of common parts in the scripts), give semantic meaning to those, and compose the returned strings without violating the DRY principle. The common parts would be extracted and reused with the safety that the desired final string is equal to the original thanks to the new unit tests.

### Test plan for issue:

Unit tests added. No behavior was changed, just extracted hardcoded values to variables and functions.

### Is there any documentation that needs to be updated for this PR?

N/A.

2022-09-15 09:43 UTC, facchettos requested changes
I think you should use embed here instead.

2022-09-19 13:49 UTC, AldoFusterTurpin commented
> I think you should use embed here instead.

Yes, I completely agree. 
Done. Thanks!

2022-09-20 15:11 UTC, facchettos submitted a review, later dismissed

2022-09-20 15:13 UTC, facchettos commented
if you want to remove these ugly new lines, you can have a new commit (keep both so we have the history and it shows that this is a wanted change) where you remove it and run make generate. Might make it a little nicer (or not). up to you, I think it's fine either way

2022-09-20 16:22 UTC, facchettos approved these changes

2022-10-19 14:49 UTC, facchettos approved these changes

2022-10-19 15:18 UTC, cblecker approved these changes

2022-10-19 15:18 UTC, merged