Updated NPM packages, resolved all dependency vulnerabilities and int…
Azure/ARO-RP pull request #2381
Opened 2022-09-06 23:46 UTC by carlowisse

### Which issue this PR addresses:
Fixes: [ADO Card](https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/14948372)

### What this PR does / why we need it:
Multiple CVE issues were identified with dependencies for portal/v2.

All dependencies have been upgraded to versions with no known vulnerabilities. Dependencies with no identified vulnerabilities have also been upgraded including webpack to ensure compatibility for future development.

Implementation of new webpack version removed default polyfill inclusions. The required polyfills for portal/v2 now have a fallback configured.

### Test plan for issue:
- Ran npm audit before upgrades: `found 29 vulnerabilities`
- Ran npm audit after upgrades/changes: `found 0 vulnerabilities`
- Manually built portal/v2 after upgrades
  - Ran local development RP
  - Hosted local portal/v2
  - Tested functionality
- Standard pipeline testing upon PR

### Is there any documentation that needs to be updated for this PR?
No - however, I have added a README for further development assistance in building and auditing the portal.

2022-09-08 06:43 UTC, ellis-johnson submitted a review, later dismissed
Looks good to me!

2022-09-12 23:46 UTC, darthhexx requested changes

2022-09-13 00:16 UTC, carlowisse commented on Makefile
> +	docker run --platform=linux/amd64 -t --rm $(REGISTRY)/linter:latest
Changes pushed, made note for documentation updating for dev environments as we specify the install of podman locally which changes the way it is run locally vs. production.

2022-09-13 01:32 UTC, darthhexx approved these changes
lgtm

2022-09-13 01:33 UTC, merged