Add resource ID param in the URL
Azure/ARO-RP pull request #2464
Opened 2022-10-14 20:15 UTC by devamanv

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2022-10-17 06:52 UTC, ellis-johnson reviewed
LGTM! Just one nitpick

2022-10-17 06:52 UTC, ellis-johnson commented on portal/v2/src/ClusterList.tsx
> +
Need to get rid of whitespace

2022-11-08 07:25 UTC, devamanv commented on portal/v2/src/ClusterList.tsx
> +
Done

2022-11-08 11:15 UTC, facchettos submitted a review, later dismissed
would be good to get rid of bindata here and use embed instead. edit: Nevermind, taken care of by shawn

2023-11-01 06:02 UTC, jaitaiwan requested changes
Provided some more feedback on the PR. A few nicks a few best practice things.

2023-11-01 06:02 UTC, jaitaiwan commented on portal/v2/src/ClusterList.tsx
> +    </>
There's only 1 top-level element `<Layer>` so the fragment `<>` is unnecessary.

2023-11-01 06:02 UTC, jaitaiwan commented on portal/v2/src/index.tsx
> +}
This is a helper function that should be extracted into some sort of libs file.

2023-11-01 06:02 UTC, jaitaiwan commented on test/e2e/admin_portal.go
> +		wd.Wait(conditions.ElementIsLocated(selenium.ByCSSSelector, "div[role='document']"))
We shouldn't have both time.Sleep and wd.Wait. We should be waiting with specific enough selectors that it executes the test when the dom is ready with the data fetched.

2023-11-01 06:02 UTC, jaitaiwan commented on test/e2e/admin_portal.go
> +		wd.Wait(conditions.ElementIsLocated(selenium.ByID, "ClusterDetailPanel"))
Same as previous comment

2024-07-02 08:27 UTC, mociarain commented
We have this now (unless I'm misunderstanding ResourceId in this context??)

Happy to close this?

2024-07-08 09:25 UTC, mociarain commented
This has been implemented here AFAIK: https://github.com/Azure/ARO-RP/pull/2640.

Closing for now but do re-open if I've misunderstood

2024-07-08 09:25 UTC, closed without merging