Revert workaround for mdsd bug
Azure/ARO-RP pull request #2471
Opened 2022-10-18 13:43 UTC by s-fairchild

### Which issue this PR addresses:

https://issues.redhat.com/browse/ARO-1535

### What this PR does / why we need it:

Remove workaround that reset log permissions to syslog. Once Microsoft fixes race condition [in this card](https://dev.azure.com/msazure/One/_workitems/edit/12512148) this PR will be ready to merge.

This PR reverts a workaround (resetting log permissions to syslog) for a MDSD race condition.
When this problem occurs, odd and hard to track down logging behavior can occur. In this case of [this ICM](https://portal.microsofticm.com/imp/v3/incidents/details/269121287/home) log messages were sent to dgrep, but not kusto. Alerts were received that AzSecPack was not running, but dgrep showed proof it was running.

On the RP VMSS an MDSD race event was occurring. Threads were using different uids to create files/directories, resulting in MDSD losing permission to those directories. See ICM comments for detailed error message examples.

The version of MDSD affected was not found in notes or attached log mesages.

### Test plan for issue:

Tested by deploying pull request to INT. [Deployment and E2E passed](https://dev.azure.com/msazure/AzureRedHatOpenShift/_releaseProgress?_a=release-pipeline-progress&releaseId=3765)

### Is there any documentation that needs to be updated for this PR?
No

2022-10-18 13:52 UTC, s-fairchild commented
@microsoft-github-policy-service agree [company="{Red Hat}"]

2022-10-18 14:37 UTC, s-amann approved these changes
lgtm, nice work! Let's continue to hold merging this until MSFT has their fix in place.

2022-10-18 16:38 UTC, ross-bryan approved these changes

2022-10-20 13:28 UTC, ross-bryan submitted a review, later dismissed

2022-11-11 18:13 UTC, SudoBrendan commented
Hey @s-fairchild - CI is failing due to not committing the files created after running `make generate`. Can you do so?

2022-11-11 18:17 UTC, SudoBrendan requested changes
I think we'll want to keep the log messages for other logic.

2022-11-11 18:17 UTC, SudoBrendan commented on pkg/deploy/generator/scripts/gatewayVMSS.sh
> -echo "enabling aro services"
I feel like we'll still want these `echo` messages for the loop that comes after

2022-11-11 18:17 UTC, SudoBrendan commented on pkg/deploy/generator/scripts/rpVMSS.sh
> -echo "enabling aro services"
same as above.

2022-11-14 17:15 UTC, s-fairchild commented
@SudoBrendan Yes, I forgot to generate the files. I'll run `make generate` and add the enabling aro services echo back.

2023-07-21 11:58 UTC, s-fairchild commented
[This pull request](https://dev.azure.com/msazure/One/_git/Compute-Runtime-Tux/pullrequest/8454967?path=/CMakeLists.txt) was merged fixing the MDSD bug.  

I'm trying to determine which image version will contain this fix. Once we have confirmed the MDSD image will be updated to include the fix we can merge/rollout this change.

2023-07-24 12:07 UTC, s-fairchild commented
Fix has been merged and [can be expected in MDSD rollout version 1.28](https://dev.azure.com/msazure/One/_workitems/edit/12512148#24894147). This PR should be merged after we've updated to the 1.28 (or later) image.

2023-08-31 23:44 UTC, bennerv commented
@s-fairchild  is this ready to go with our most recent MDSD bump?  #3106

2023-08-31 23:52 UTC, s-fairchild commented
@bennerv Yes, it's ready with the next MDSD image update.

2023-09-21 13:24 UTC, s-fairchild commented
[Deployment and E2E passed in INT](https://dev.azure.com/msazure/AzureRedHatOpenShift/_releaseProgress?_a=release-pipeline-progress&releaseId=3765)

2023-09-21 14:09 UTC, s-amann approved these changes

2023-10-04 23:44 UTC, hlipsig commented
Dependency for this card is completed, but card is over a year old. Closing and @s-fairchild  if this is needed please re-open.

2023-10-12 13:04 UTC, s-fairchild commented
@hlipsig Confirming that the dependency card had been completed took some time. After this I needed to test in INT. This PR is ready to merge for the next release.

2023-10-13 14:19 UTC, cadenmarchese approved these changes

2023-10-17 14:02 UTC, merged