Split the image mirroring up so that it can run piecemeal
Azure/ARO-RP pull request #2496
Opened 2022-10-28 01:27 UTC by hawkowl

### Which issue this PR addresses:

Part of https://dev.azure.com/msazure/AzureRedHatOpenShift/_workitems/edit/16033731

### What this PR does / why we need it:

Breaks apart the image mirroring a little, so that each part can be run alone, and the OpenShift portion can be broken up to individual tasks for each minor version.

### Test plan for issue:

A bit of minor local testing, although this shouldn't break the existing pipelines

### Is there any documentation that needs to be updated for this PR?
Not yet

2022-10-28 08:09 UTC, facchettos requested changes
some suggestions + a question

2022-10-28 08:09 UTC, facchettos commented on cmd/aro/mirror.go
> +	}
it probably would be better to have a proper function definition for that

2022-10-28 09:59 UTC, facchettos commented on cmd/aro/main.go
> +	}
maybe we can look into tabwriter ? https://pkg.go.dev/text/tabwriter

2022-10-31 04:02 UTC, hawkowl commented on pkg/util/version/version.go
>  	V      [3]uint32
No clue :)

2023-10-04 23:45 UTC, hlipsig commented
Closing old PR's. Please open again if needed.

2023-10-04 23:45 UTC, closed without merging