Containerize CI pipeline
Azure/ARO-RP pull request #2583
Opened 2022-12-07 09:48 UTC by SrinivasAtmakuri

With this commit, the CI jobs running in shell will run inside containers.

### Which issue this PR addresses:

Fixes: https://msazure.visualstudio.com/AzureRedHatOpenShift/_workitems/edit/16018371/

### What this PR does / why we need it:

### Test plan for issue:

Testing done: https://github.com/Azure/ARO-RP/pull/2557

### Is there any documentation that needs to be updated for this PR?

2022-12-09 02:03 UTC, darthhexx requested changes
I have raised this before, but I am not seeing any mention in this PR of the fact that this is change going to prevent all Admin Portal E2E tests from executing.

That is going to open us up to potential issues, like we recently had when all Admin Portal tests were disabled by mistake, instead of just tests in production, that resulted in a broken Admin Portal being deployed to production.

We need a plan to work around this issue and that work needs to be ready to commit, before this PR is merged.

2022-12-16 10:46 UTC, facchettos requested changes
already talked with srini about it on slack, but for the record, this is breaking the github action with the change from run to entryproint.

2023-01-02 12:58 UTC, facchettos commented on Dockerfile.python
> +    microdnf clean all
does that mean that we will update all the packages before every run ? couldn't we build an image with those built in so we don't have to redownload and apply those everytime?

2023-01-09 11:31 UTC, SrinivasAtmakuri commented
A better approach is being tested here: https://github.com/Azure/ARO-RP/pull/2624. With the current approach of this PR, Golang runs are taking longer to run inside the custom build image, the 2624 approach doesn't seem to have this problem.

2023-01-09 11:31 UTC, closed without merging