Ensure monitor captures the deletion
Azure/ARO-RP pull request #2597
Opened 2022-12-14 11:14 UTC by yehornaumenko

Update the process of cluster deletion.
Ensure that the OpenShiftClusterDocument is
in the DeletingProvisioningState for at least
20 seconds.

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2022-12-14 21:58 UTC, jhoreman commented
Hey Yehor, thanks for this. Can we include the work item associated with this PR? Would like to know more about the reasoning and goals behind this change.

2022-12-20 14:53 UTC, yehornaumenko commented
Hi @jhoreman. I have updated the description of this PR, could you check it, please?

2022-12-20 19:56 UTC, jhoreman commented
> Hi @jhoreman. I have updated the description of this PR, could you check it, please?

Perfect! Thanks for adding all this detail.

2023-01-05 01:29 UTC, darthhexx requested changes

2023-01-05 01:29 UTC, darthhexx commented on pkg/backend/openshiftcluster.go
> +		time.Sleep(time.Until(t.Add(time.Second * 20)))
Adding 20 seconds to _every_ cluster delete is not a great customer experience to introduce for this edge case. Ideally we would follow the [recommended delete approach of using a TTLs](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-design-patterns#deletes), 10 seconds in our case, but due to use-cases where users are creating and tearing down clusters using the same name/RG/VNET, etc, we may run into issues when the TTL has not expired yet.

To limit the effect of this change, wouldn't it make sense to add a `deleteStartedAt := time.Now()` variable before `err = m.Delete(ctx)`, and then only sleep here if the delete has taken less than 10 seconds? Or 15 to be absolutely certain.

2023-01-05 01:34 UTC, darthhexx approved these changes

2023-01-05 01:34 UTC, darthhexx commented on pkg/backend/openshiftcluster.go
> +		time.Sleep(time.Until(t.Add(time.Second * 20)))
Ignore my first comment. I see that you have added a conditional sleep on the deletion start time.

2023-01-05 01:58 UTC, darthhexx commented on pkg/backend/openshiftcluster.go
> +		time.Sleep(time.Until(t.Add(time.Second * 20)))
Ignore my previous comment, I see you have added a conditional sleep using the deletion start time.

2023-01-05 13:05 UTC, petrkotas approved these changes
@yehornaumenko perfect, this is exactly the good enough for now solution, we agreed upon. It will allow us to resolve some sev2.

In the future, we can improve the deletion mechanism.

2023-01-05 13:09 UTC, facchettos commented on docs/monitoring.md
> +  The monitor reads the change feed every 10 seconds, so we should except exclude
```suggestion
  The monitor reads the change feed every 10 seconds, so we should expect exclude
```

2023-01-05 13:13 UTC, facchettos approved these changes
lgtm, little typos but that can be fixed later

2023-01-05 13:14 UTC, merged