Update the list of AKS denied regions
Azure/ARO-RP pull request #2669
Opened 2023-01-30 15:53 UTC by petrkotas

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:
Provide updated list of regions without working AKS. 

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

2023-01-30 21:16 UTC, bennerv approved these changes

2023-01-30 21:17 UTC, bennerv requested changes

2023-01-30 21:17 UTC, bennerv commented on test/e2e/aks.go
> +	regionswithoutAKS := []string{
Typo:
```suggestion
regionsWithoutAKS := []string{

2023-01-31 11:07 UTC, UlrichSchlueter reviewed
The list is correct.

2023-01-31 13:24 UTC, facchettos approved these changes

2023-01-31 13:24 UTC, merged