Hawkowl/proxy rhel8
Azure/ARO-RP pull request #2773
Opened 2023-03-14 23:43 UTC by hawkowl

### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-2526

### What this PR does / why we need it:
Updates the proxy to run on RHEL8, and also has a multi-stage image because I'm scared that my Fedora box will have a different glibc :)

### Test plan for issue:
E2E infra, so, if the e2e still works?

### Is there any documentation that needs to be updated for this PR?
N/A

2023-03-14 23:46 UTC, cblecker approved these changes

2023-03-14 23:47 UTC, cblecker requested changes

2023-03-14 23:47 UTC, cblecker commented on Dockerfile.proxy
> +RUN make proxy RELEASE=${IS_OFFICIAL_RELEASE} -o generate
Does this need to be an ARG too?

2023-03-14 23:50 UTC, cblecker submitted a review, later dismissed

2023-03-15 00:08 UTC, ellis-johnson approved these changes
LGTM!

2023-03-15 09:57 UTC, SrinivasAtmakuri approved these changes
LGTM!

2023-03-15 19:04 UTC, bennerv approved these changes
lgtm

2023-03-16 19:17 UTC, cadenmarchese approved these changes

2023-03-16 19:17 UTC, merged