Rewrite some of the cert/key encoding and decoding
Azure/ARO-RP pull request #2854
Opened 2023-04-19 00:26 UTC by hawkowl

### Which issue this PR addresses:
Splitting out some of #2842 that is unrelated

### What this PR does / why we need it:

Rewrites some of the PEM encoding/decoding which will be used when the installer dependencies are removed

### Test plan for issue:
Unit tests, should mostly be a no-op

### Is there any documentation that needs to be updated for this PR?
N/A

2023-05-01 22:40 UTC, SudoBrendan requested changes
Overall, looks really good! I think adding context for each `t.Fatal` in some way would be helpful.

2023-05-01 22:40 UTC, SudoBrendan commented on pkg/util/pem/pem_test.go
> +func TestEncode(t *testing.T) {
It looks like this one function has multiple given/when/then test cases centered around `Encode` calls. Can we break out each of these into named `t.Run` clauses to give some context for each, which would have added benefit to adding context to each `t.Fatal` (which, as it stands now, would be hard to know at which point something went wrong)

2023-05-17 02:49 UTC, jaitaiwan reviewed
Agree w/ Brendan's comments, apart from that LGTM

2023-05-19 05:18 UTC, jaitaiwan requested changes

2023-05-19 05:18 UTC, jaitaiwan commented on pkg/util/pem/pem_test.go
Since we're doing more verbal-like testing, I'd personally expect something like:
```
describe "pem cert package"
  describe "certificate encoding keys"
    it "successfully encodes a private key"
```

etc etc

2023-05-19 05:18 UTC, jaitaiwan commented on pkg/util/pem/pem_test.go
So more "wordy" or "explanatory" in the descriptions.

2023-05-19 14:30 UTC, s-amann commented on pkg/env/certificateRefresher_test.go
> -// TODO: Remove once ARO is on go1.15
whoot its about time!

2023-05-19 14:32 UTC, s-amann approved these changes

2023-05-21 23:58 UTC, ellis-johnson approved these changes
LGTM!

2023-05-22 01:12 UTC, merged