[] Adding version in log
Azure/ARO-RP pull request #2869
Opened 2023-04-25 04:18 UTC by sankur-codes

### Which issue this PR addresses:

Fixes [ARO-2786](https://issues.redhat.com/browse/ARO-2786)

### What this PR does / why we need it:

This PR includes a new field **_`version`_** in RP logs which has the value of Openshift cluster version. This is later intended to be able to grab it out of the logs and update our dashboards based on cluster installation or failure on it

### Test plan for issue:

In Progress

### Is there any documentation that needs to be updated for this PR?

No

2023-04-26 05:16 UTC, ellis-johnson requested changes
LGTM! Have one comment about left over portal changes and still needs tests

2023-04-26 05:16 UTC, ellis-johnson commented on pkg/portal/assets/v2/build/asset-manifest.json
> +    "main.js": "/static/js/main.0b4eab3b.js",
Why are all these portal assets included? Was this an accidental change?

2023-04-26 08:58 UTC, sankur-codes commented
> LGTM! Have one comment about left over portal changes

2023-04-27 00:49 UTC, hawkowl submitted a review, later dismissed
We already collect this information in Geneva for dashboards -- is there a usage gap that I am not aware of?

2023-04-27 04:16 UTC, ellis-johnson commented
> We already collect this information in Geneva for dashboards -- is there a usage gap that I am not aware of?

Where abouts is it stored? Or where do we use it in geneva? The premise behind this change is to use this information to check install success between different versions

2023-05-02 16:56 UTC, SudoBrendan approved these changes
This LGTM if it's needed, pending discussions already here.

2023-05-02 22:35 UTC, bennerv commented
@hawkowl
> We already collect this information in Geneva for dashboards -- is there a usage gap that I am not aware of?

Our cluster failure dashboards key off of cluster logs to determine why a cluster failed to install, and report it up in a dashboard.  So the goal is to aggregate dashboards + minor versions + failure reasons.  It's not as simple as using existing metrics as a result :/

2023-05-02 23:30 UTC, merged