ARO-1423 and ARO-1422: Deny Editing ClusterVersion and UpgradeConfig
Azure/ARO-RP pull request #2975
Opened 2023-06-22 07:05 UTC by edisonLcardenas

### Which issue this PR addresses:

[ARO-1422: UpgradeConfig](https://issues.redhat.com/browse/ARO-1422)
[ARO-1423: ClusterVersion](https://issues.redhat.com/browse/ARO-1423)

### What this PR does / why we need it:
Block editing of  ClusterVersion and UpgradeConfig by regular users. This will reduce amount of ticket we receive due to customers trying to do an unsupported action. We have a policy that will deny regulars users editing of ClusterVersion and UpgradeConfig.

### Test plan for issue:
* OPA Tests - **Passed**
* Gator Tests - **Passed**
* Real Cluster Verification - **Passed**
* Web Console Test - **Passed**

For detailed test result, please see the jiras above.

### Is there any documentation that needs to be updated for this PR?
Yes, the README for guardrails. Included  info on how to create policies that needs to sync data into OPA using data.inventory object.

2023-06-27 06:44 UTC, ArrisLee requested changes
left a comment, I think we may be able to let these two constraints share the same template

2023-06-27 06:44 UTC, ArrisLee commented on pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-clusterversion.yaml
> +        	regex.match("source: OCM", config_data)
ok, looks like this template is quite identical to the `aro-deny-upgradeconfig` one, so my understanding is, we need two different constraints to facilitate different matches, but can use reuse the template at least?

2023-06-29 00:38 UTC, ArrisLee requested changes
overall LGTM, left some comments and please fix lint warning

2023-06-29 00:38 UTC, ArrisLee commented on pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-clusterversion-upgradeconfig/src.rego
> +	msg := "Modifying this resource is not allowed for regular users. This includes attempting to create, edit, or delete."
I think we may need to provide a bit more info here, the condition here should be `MUO` is enabled right?

2023-06-29 00:38 UTC, ArrisLee commented on pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-clusterversion-upgradeconfig/src_test.rego
> +
I see you have combine `clusterversion` and `upgradeconfig` logics together as one constraint template, so do we need some more test cases here to cover `clusterversion` checks?

2023-06-29 01:55 UTC, ArrisLee approved these changes
LGTM

2023-06-29 02:30 UTC, yjst2012 requested changes
left a few comments, pls have a look, thanks.

2023-06-29 02:30 UTC, yjst2012 commented on pkg/operator/controllers/guardrails/policies/gkconstraints/aro-clusterversion-upgradeconfig-deny.yaml
> +  name: aro-deny-clusterversion-upgradeconfig-modification
we want to have the same .metadata.name as the filename of the constraint to keep feature flag name and constraint name consistent, so can you please rename it to aro-clusterversion-upgradeconfig-deny

2023-06-29 02:30 UTC, yjst2012 commented on pkg/operator/controllers/guardrails/policies/README.md
> +Make sure the filename of constraint is the same as the .metadata.name of the Constraint object, as it is the feature flag name that will be used to turn on / off the policy.
why is the moving? feel like it is a note to the constraint section?

2023-06-29 02:30 UTC, yjst2012 commented on pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-clusterversion-upgradeconfig/sync.yaml
> +          "openshift-service-ca*",
IIUC, as per [gk doc](https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces/) this is excluding priv'd namespaces from gatekeeper's control, which will left them unprotected by our priv'd ns policy, isn't it?

2023-06-29 02:30 UTC, yjst2012 commented on pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-clusterversion-upgradeconfig/sync.yaml
> +apiVersion: config.gatekeeper.sh/v1alpha1
as to sync.yaml, need to move it to somewhere global to all policies and find a way to auto deploy it, we can put it here for now.

2023-06-29 03:33 UTC, yjst2012 commented on pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-clusterversion-upgradeconfig/sync.yaml
> +          "openshift-service-ca*",
can you please test this out, by checking after this applied if the priv'd ns policy still work?

2023-07-11 05:13 UTC, merged