Addressing REGISTRY env in Makefile
Azure/ARO-RP pull request #3299
Opened 2023-11-29 20:49 UTC by Shivkumar13

### What this PR does / why we need it:

Fixes the issue with the `RP_IMAGE_ACR` env, as when `$(RP_IMAGE_ACR)`  is empty, the `$ARO_IMAGE_BASE` would be `.azurecr.io/aro`, which will fail any operations that we do with the image.

Encountered this issue while the `RP_IMAGE_ACR` is not set, and also the else if conditions seems unnecessary as we are defaulting to registry.access.redhat.com in the else block so no need to check `RP_IMAGE_ACR` explicitly  for the empty value. 

### Test plan for issue:
N/A

### Is there any documentation that needs to be updated for this PR?
N/A

2023-11-29 22:40 UTC, jhoreman approved these changes
Seems straightforward enough. Thanks for this.

2023-11-30 14:57 UTC, Shivkumar13 commented
/azp run e2e

2023-12-18 02:55 UTC, anshulvermapatel approved these changes
/lgtm

2023-12-18 02:55 UTC, anshulvermapatel commented
/azp run e2e

2024-01-16 16:54 UTC, SudoBrendan requested changes
I worry about this change because it has wider implications to our pipelines, where this variable is set and overridden, e.g. https://github.com/Azure/ARO-RP/blob/master/.pipelines/e2e.yml#L42

What is the pain we are trying to mitigate here? I feel like if someone doesn't run `make secrets` + `. ./env` other issues will also arise outside this.

2024-07-25 06:43 UTC, mociarain commented
Closing this since it's stale and has no associated ticket. Push back if this seems worth pursuing

2024-07-25 06:43 UTC, closed without merging