ARO-4745: Update cluster lifecycle API fields to readOnly
Azure/ARO-RP pull request #3369
Opened 2024-01-24 21:09 UTC by lranjbar

### Which issue this PR addresses:

Fixes ARO-4745

### What this PR does / why we need it:

This PR sets a handful of fields in the API to be read only because they don't change once set. Changing the values in these fields would create unexpected functionality for the RP.

2024-01-24 21:17 UTC, SudoBrendan requested changes

2024-01-24 21:17 UTC, SudoBrendan commented on pkg/api/v20231122/openshiftcluster.go
> +	ConsoleProfile ConsoleProfile `json:"consoleProfile,omitempty" swagger:"readOnly"`
I think instead of making the whole `Profile` readonly, we just want the URL (which, yea, is the only thing in there... but... (see L122)

2024-01-24 21:17 UTC, SudoBrendan commented on pkg/api/v20231122/openshiftcluster.go
> +	APIServerProfile APIServerProfile `json:"apiserverProfile,omitempty" swagger:"readOnly"`
Same as above, instead of `Profile`, let's do the specific field of the URL (L252)

2024-01-24 22:09 UTC, SudoBrendan submitted a review, later dismissed
LGTM, thanks!

2024-01-26 08:57 UTC, mociarain submitted a review, later dismissed
LGTM

2024-01-29 17:28 UTC, bennerv reviewed
Can we update the existing field which are readonly in swagger to have the swagger `readOnly` tag?

2024-02-07 22:08 UTC, closed without merging

2024-02-07 22:08 UTC, tsatam commented
Follow #3380 for the implementation of this change