Update `az aro` permissions validation to mirror RP frontend validation
Azure/ARO-RP pull request #3395
Opened 2024-02-08 22:47 UTC by tsatam

### Which issue this PR addresses:

Fixes [ARO-5075](https://issues.redhat.com/browse/ARO-5075)

### What this PR does / why we need it:

Updates the dynamic validation performed by the Azure CLI `az aro` command to mirror the validation performed by the RP itself. 

### Test plan for issue:

Unit tests were added for the dynamic validator's `can_do_action` function. These tests mirror the equivalent tests for the RP's validation. 

### Is there any documentation that needs to be updated for this PR?

No

### Review breadcrumbs

Code to compare against:
- [RP implementation](https://github.com/Azure/ARO-RP/blob/master/pkg/util/permissions/permissions.go)
- [RP tests](https://github.com/Azure/ARO-RP/blob/master/pkg/util/permissions/permissions_test.go)

2024-02-09 13:40 UTC, mociarain requested changes
So functionally I agree that this works but it's very odd to me that `can_do_action` is returning essentially an `Optional[ErrorString]` and not a boolean.

IMO this would be clearer and more idiomatic if it returned a boolean and then we added the error message up a level in the `validate_resource` on the basis of that. 

What do you think?

2024-02-09 14:56 UTC, mociarain commented
> given that we're actively investigating moving _all_ of this validation logic into the RP and having the `az aro validate` command that uses this validation to just call an API endpoint instead.

Oh in that case then I get it. Thanks for the explication and :ship:  ;)

2024-02-09 14:56 UTC, mociarain approved these changes

2024-02-09 14:59 UTC, tsatam commented
> > given that we're actively investigating moving _all_ of this validation logic into the RP and having the `az aro validate` command that uses this validation to just call an API endpoint instead.
> 
> Oh in that case then I get it. Thanks for the explication and 🚢 ;)

I changed my mind, I pushed up this refactor on a new commit.

2024-02-09 15:08 UTC, mociarain approved these changes
Double approved ;)

2024-02-09 16:16 UTC, SudoBrendan approved these changes

2024-02-19 19:44 UTC, s-amann approved these changes
:shipit:

2024-02-19 19:45 UTC, merged