Minimal Python container to build `az aro` extension
Azure/ARO-RP pull request #3490
Opened 2024-04-01 16:00 UTC by tsatam

(This PR recreates #3439 off of in-repository branch for CI checks)

### Which issue this PR addresses:

Small step for [ARO-5088](https://issues.redhat.com/browse/ARO-5088)

### What this PR does / why we need it:

- Creates a new Makefile target to build the `az aro` extension with no other dependencies
- Adds a new containerfile to create a build container for the above

### Test plan for issue:

Manually invoke target and ensure it creates an `aro-${VERSION}-py2.py3-none-any.whl` file within `./python/az/aro/dist`. 

### Is there any documentation that needs to be updated for this PR?

Eventually, https://msazure.visualstudio.com/AzureRedHatOpenShift/_wiki/wikis/ARO.wiki/188187/AzureCLI-preview-extension-publishing# should be updated to include this target. 

### Additional Notes
- This container does not perform the verification steps performed by the `azdev` command (`style`/`linter`/`test`). `azdev` requires that it be run within the context of a Git repository, as well as from within a specific virtualenv.

2024-04-01 16:23 UTC, SudoBrendan approved these changes

2024-04-01 19:07 UTC, cadenmarchese submitted a review, later dismissed
makes sense 👍

2024-04-17 17:55 UTC, cadenmarchese commented
/azp run ci,e2e

2024-06-05 16:10 UTC, SudoBrendan requested changes
Just a quick typo fix. Otherwise, builds fine!

2024-06-05 16:10 UTC, SudoBrendan commented on Makefile
> +.PHONY: admin.kubeconfig aks.kubeconfig aro az azext_aro ci-portal ci-rp clean client deploy dev-config.yaml discoverycache fix-macos-vendor generate image-aro-multistage image-fluentbit image-proxy
```suggestion
.PHONY: admin.kubeconfig aks.kubeconfig aro az azext-aro ci-portal ci-rp clean client deploy dev-config.yaml discoverycache fix-macos-vendor generate image-aro-multistage image-fluentbit image-proxy init-contrib lint-go runlocal-rp proxy publish-image-aro-multistage publish-image-fluentbit publish-image-proxy secrets secrets-update e2e.test tunnel test-e2e test-go test-python vendor build-all validate-go unit-test-go coverage-go validate-fips install-go-tools
```

2024-06-06 01:49 UTC, hawkowl commented
/azp run ci, e2e

2024-06-06 20:23 UTC, SudoBrendan approved these changes
LGTM

2024-06-06 21:07 UTC, SudoBrendan approved these changes

2024-06-06 21:17 UTC, tony-schndr approved these changes
LGTM

2024-06-07 15:58 UTC, shubhadapaithankar approved these changes
LGTM

2024-06-07 22:34 UTC, SudoBrendan commented
/azp run ci

2024-06-07 22:54 UTC, merged