Modified the content to set up the dev env  : ARO-7278
Azure/ARO-RP pull request #3554
Opened 2024-05-01 21:28 UTC by shubhadapaithankar

### Which issue this PR addresses:
Fix the `github.user` doc
Fix the `az` cli doc for setting envvar rather than ~/.config

### What this PR does / why we need it:
This PR updates the developer onboarding documentation.

### Test plan for issue:
 Documented how to manually test and verify the feature

### Is there any documentation that needs to be updated for this PR?
N/A

### How do you know this will function as expected in production? 
N/A

2024-05-01 21:42 UTC, SudoBrendan requested changes
LGTM, except a small typo at the top of the deploy-dev-rp.md file

2024-05-01 21:42 UTC, SudoBrendan commented on docs/deploy-development-rp.md
> -# Deploy development RP
I think this is a typo

2024-05-01 21:44 UTC, shubhadapaithankar commented
@microsoft-github-policy-service agree company="Red Hat"

2024-05-01 22:14 UTC, SudoBrendan approved these changes

2024-05-01 22:17 UTC, shubhadapaithankar commented on docs/deploy-development-rp.md
> -# Deploy development RP
Fixed it.

2024-05-01 22:36 UTC, kimorris27 approved these changes

2024-05-02 07:25 UTC, anshulvermapatel approved these changes

2024-05-02 07:29 UTC, anshulvermapatel commented
/azp run e2e, ci

2024-05-02 07:30 UTC, mociarain approved these changes

2024-05-02 11:49 UTC, tsatam approved these changes

2024-05-02 15:39 UTC, SudoBrendan commented
/azp run e2e

2024-05-03 20:25 UTC, merged