Enable additional statickchecks
Azure/ARO-RP pull request #3726
Opened 2024-07-26 17:38 UTC by bitoku

### Which issue this PR addresses:

Fixes [suggestion here](https://github.com/Azure/ARO-RP/pull/3721#discussion_r1693219947)

### What this PR does / why we need it:

This PR enables "-ST1020", "-ST1021", "-ST1022" checks to make the code more consistent.
Some codes don't follow these lint, so I also enables `only-new-issues` in golangci-lint-action.

Any concerns and comments about enabling `only-new-issues` are welcome. 

cf
https://staticcheck.dev/docs/checks/#ST1020
https://staticcheck.dev/docs/checks/#ST1021
https://staticcheck.dev/docs/checks/#ST1022
https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#only-new-issues

### Test plan for issue:

Run CI.

### Is there any documentation that needs to be updated for this PR?

tech debt cleanup N/A

### How do you know this will function as expected in production? 

This is a part of tests.

2024-07-29 11:25 UTC, mociarain commented
/azp run ci

2024-07-29 11:53 UTC, mociarain approved these changes
I like this but I think we should get some wider buy-in. Maybe pick 2 files at random to show the change as part of this PR? Personally, happy to ship as is though if others agree.

2024-07-30 09:30 UTC, bitoku commented
/azp run ci

2024-07-30 09:40 UTC, bitoku commented
@mociarain Thanks! I updated the description.

2024-08-16 16:32 UTC, tiguelu approved these changes
I don't have a strong opinion in favour or against.

It looks like the original commit was enabling these cheeks and they were disabled at a later point under the assumption they had to match the default value.

There has been no feedback against it in 3 weeks, so I'm happy to get it merged. If there is any feedback against the change after enablement, we can always revert it.

2024-08-19 20:31 UTC, SudoBrendan reviewed
I also don't have an opinion either way on these specific linting rules.

I do think, if we are looking for conformity and we consider these rules to be important enough to conform on, that it's best to not use `only-new-issues: true`. It feels odd to have an overwhelming majority of our codebase not conforming to a linting rule we think is important. What would it take to add those fixes here?

2024-08-19 20:39 UTC, SudoBrendan requested changes
This PR currently breaks `make ci-rp`. Can you please rebase on master and fix that workflow? The error I see is:

```
Error: building at STEP "RUN golangci-lint run --verbose": while running runtime: exit status 1
```

2024-08-19 20:39 UTC, SudoBrendan commented on .golangci.yml
modifying this .golangci.yml, but not modifying `Dockerfile.ci-rp` results in failures for `make ci-rp`. This doesn't show up in the pipelines today, but it will soon. If you rebase on master and run `make ci-rp` you'll see these new rules executing as part of the containerized build process and failing.

2024-08-20 08:35 UTC, bitoku commented
@SudoBrendan 
As described in the description, there's a lot of places we need to fix.

There's nothing blocking from fixing those changes, but it needs time and effort because we don't want to just fix the lint errors but want to have proper doc comments for those.

<details><summary>The current lint errors we get:</summary>
<p>

```
::error file=pkg/util/azureclient/mgmt/compute/diskencryptionsets.go,line=26,col=1::ST1020: comment on exported function NewDiskEncryptionSetsClient should be of the form "NewDiskEncryptionSetsClient ..." (stylecheck)
::error file=pkg/api/v20231122/openshiftcluster_example.go,line=51,col=1::ST1020: comment on exported function ExampleOpenShiftClusterGetResponse should be of the form "ExampleOpenShiftClusterGetResponse ..." (stylecheck)
::error file=pkg/api/v20231122/openshiftcluster_example.go,line=71,col=1::ST1020: comment on exported function ExampleOpenShiftClusterPutOrPatchResponse should be of the form "ExampleOpenShiftClusterPutOrPatchResponse ..." (stylecheck)
::error file=pkg/api/v20231122/clustermanager.go,line=81,col=1::ST1021: comment on exported type SyncIdentityProviderList should be of the form "SyncIdentityProviderList ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20231122/clustermanager.go,line=113,col=1::ST1021: comment on exported type SyncIdentityProviderProperties should be of the form "SyncIdentityProviderProperties ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20231122/openshiftcluster.go,line=134,col=1::ST1021: comment on exported type OutboundType should be of the form "OutboundType ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20231122/openshiftcluster.go,line=217,col=1::ST1021: comment on exported type VMSize should be of the form "VMSize ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20220904/clustermanager.go,line=81,col=1::ST1021: comment on exported type SyncIdentityProviderList should be of the form "SyncIdentityProviderList ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20220904/clustermanager.go,line=113,col=1::ST1021: comment on exported type SyncIdentityProviderProperties should be of the form "SyncIdentityProviderProperties ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20220904/openshiftcluster.go,line=162,col=1::ST1021: comment on exported type VMSize should be of the form "VMSize ..." (with optional leading article) (stylecheck)
::error file=pkg/gateway/gateway.go,line=85,col=1::ST1022: comment on exported const SocketSize should be of the form "SocketSize ..." (stylecheck)
::error file=pkg/util/steps/refreshing.go,line=23,col=1::ST1020: comment on exported function AuthorizationRetryingAction should be of the form "AuthorizationRetryingAction ..." (stylecheck)
::error file=pkg/frontend/middleware/maintenance.go,line=20,col=1::ST1020: comment on exported method UnplannedMaintenanceSignal should be of the form "UnplannedMaintenanceSignal ..." (stylecheck)
::error file=pkg/frontend/middleware/metrics.go,line=22,col=1::ST1020: comment on exported method Metrics should be of the form "Metrics ..." (stylecheck)
::error file=pkg/util/oidcbuilder/jwks.go,line=52,col=1::ST1020: comment on exported function BuildJSONWebKeySet should be of the form "BuildJSONWebKeySet ..." (stylecheck)
::error file=pkg/api/v20230701preview/clustermanager.go,line=81,col=1::ST1021: comment on exported type SyncIdentityProviderList should be of the form "SyncIdentityProviderList ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20230701preview/clustermanager.go,line=113,col=1::ST1021: comment on exported type SyncIdentityProviderProperties should be of the form "SyncIdentityProviderProperties ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20230701preview/openshiftcluster.go,line=131,col=1::ST1021: comment on exported type OutboundType should be of the form "OutboundType ..." (with optional leading article) (stylecheck)
::error file=pkg/api/v20230701preview/openshiftcluster.go,line=213,col=1::ST1021: comment on exported type VMSize should be of the form "VMSize ..." (with optional leading article) (stylecheck)
::error file=pkg/portal/prometheus/proxy.go,line=104,col=1::ST1020: comment on exported method ModifyResponse should be of the form "ModifyResponse ..." (stylecheck)
::error file=test/util/serversideapply/serversideapply.go,line=19,col=1::ST1020: comment on exported function CliWithApply should be of the form "CliWithApply ..." (stylecheck)
::error file=pkg/portal/cluster/clusteroperators.go,line=13,col=1::ST1021: comment on exported type OperatorCondition should be of the form "OperatorCondition ..." (with optional leading article) (stylecheck)
::error file=pkg/portal/cluster/clusteroperators.go,line=22,col=1::ST1021: comment on exported type OperatorInformation should be of the form "OperatorInformation ..." (with optional leading article) (stylecheck)
::error file=pkg/portal/cluster/statistics.go,line=23,col=1::ST1021: comment on exported type Metrics should be of the form "Metrics ..." (with optional leading article) (stylecheck)
::error file=pkg/util/pullsecret/pullsecret.go,line=21,col=1::ST1020: comment on exported function UnmarshalSecretData should be of the form "UnmarshalSecretData ..." (stylecheck)
::error file=pkg/monitor/monitoring/interface.go,line=16,col=1::ST1021: comment on exported type NoOpMonitor should be of the form "NoOpMonitor ..." (with optional leading article) (stylecheck)
::error file=pkg/api/clustermanagerdocument.go,line=6,col=1::ST1021: comment on exported type ClusterManagerConfigurationDocuments should be of the form "ClusterManagerConfigurationDocuments ..." (with optional leading article) (stylecheck)
::error file=pkg/api/clustermanagerdocument.go,line=19,col=1::ST1021: comment on exported type ClusterManagerConfigurationDocument should be of the form "ClusterManagerConfigurationDocument ..." (with optional leading article) (stylecheck)
::error file=pkg/api/openshiftcluster.go,line=234,col=1::ST1021: comment on exported type OperatorFlags should be of the form "OperatorFlags ..." (with optional leading article) (stylecheck)
::error file=pkg/api/openshiftcluster.go,line=294,col=1::ST1021: comment on exported type SoftwareDefinedNetwork should be of the form "SoftwareDefinedNetwork ..." (with optional leading article) (stylecheck)
::error file=pkg/api/openshiftcluster.go,line=311,col=1::ST1021: comment on exported type OutboundType should be of the form "OutboundType ..." (with optional leading article) (stylecheck)
::error file=pkg/api/operation.go,line=42,col=1::ST1022: comment on exported var OperationResultsRead should be of the form "OperationResultsRead ..." (stylecheck)
::error file=pkg/api/register.go,line=3,col=1::ST1022: comment on exported const APIVersionKey should be of the form "APIVersionKey ..." (stylecheck)
::error file=pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go,line=50,col=1::ST1020: comment on exported function NewReconciler should be of the form "NewReconciler ..." (stylecheck)
::error file=pkg/api/v20220401/openshiftcluster.go,line=162,col=1::ST1021: comment on exported type VMSize should be of the form "VMSize ..." (with optional leading article) (stylecheck)
::error file=pkg/mirror/mirror.go,line=58,col=1::ST1020: comment on exported function Dest should be of the form "Dest ..." (stylecheck)
::error file=pkg/mirror/mirror.go,line=67,col=1::ST1020: comment on exported function DestLastIndex should be of the form "DestLastIndex ..." (stylecheck)
::error file=pkg/deploy/config.go,line=108,col=1::ST1021: comment on exported type CosmosDBConfiguration should be of the form "CosmosDBConfiguration ..." (with optional leading article) (stylecheck)
::error file=pkg/util/graph/graphsdk/applications/item_add_password_post_request_body.go,line=13,col=1::ST1021: comment on exported type ItemAddPasswordPostRequestBody should be of  [...]

2024-08-20 16:37 UTC, bitoku commented
On second thoughts, if we run lint in local it gives a lot of errors.
This should be red herrings and we don't want this every time we run lint.

I think this lint is important for us, but considering it, I'm closing this PR.

2024-08-20 16:37 UTC, closed without merging