This is the new CI-RP stage for the pipline
Azure/ARO-RP pull request #3753
Opened 2024-08-02 16:36 UTC by shubhadapaithankar

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

### How do you know this will function as expected in production?

2024-08-02 16:45 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
hey, let's remove these spaces!

```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:47 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:48 UTC, SudoBrendan commented on .pipelines/ci.yml
> +
```suggestion

```

2024-08-02 16:48 UTC, shubhadapaithankar commented on .pipelines/ci.yml
> +
Removed the space

2024-08-02 16:58 UTC, SudoBrendan commented
/azp run ci

2024-08-02 17:39 UTC, SudoBrendan commented
/azp run ci

2024-08-02 17:41 UTC, SudoBrendan commented
/azp run ci

2024-08-02 17:44 UTC, SudoBrendan commented
/azp run ci

2024-08-02 18:24 UTC, SudoBrendan commented
/azp run ci

2024-08-02 19:06 UTC, SudoBrendan commented
/azp run ci

2024-08-02 20:25 UTC, shubhadapaithankar commented
/azp run ci

2024-08-02 20:25 UTC, SudoBrendan commented
/azp run ci

2024-08-02 20:30 UTC, SudoBrendan commented
/azp run ci

2024-08-02 20:49 UTC, SudoBrendan commented
/azp run ci

2024-08-06 15:22 UTC, SudoBrendan requested changes

2024-08-06 15:22 UTC, SudoBrendan commented on .pipelines/ci.yml
> +            if [[ "$BUILD_REASON" == "PullRequest" ]];
```suggestion
            if [[ "##vso[Build.Reason]" == "PullRequest" ]];
```

2024-08-06 15:29 UTC, shubhadapaithankar commented
/azp run ci

2024-08-06 23:00 UTC, shubhadapaithankar commented
/azp run ci

2024-08-07 18:15 UTC, SudoBrendan approved these changes

2024-08-07 18:15 UTC, SudoBrendan commented
/azp run ci

2024-08-09 18:49 UTC, SudoBrendan requested changes

2024-08-09 18:49 UTC, SudoBrendan commented on .pipelines/ci.yml
> -      options: --user=0
we need this back :)

2024-08-09 22:52 UTC, merged