Remove timeout for Hive installation
Azure/ARO-RP pull request #3765
Opened 2024-08-08 14:05 UTC by razo7

### Which issue this PR addresses:

Hive installation was timed out using the `hack/hive-dev-install.sh` script.

> .
> .
> .
> clusterrolebinding.rbac.authorization.k8s.io/hive-operator-rolebinding created
> deployment.apps/hive-operator created
> deployment.apps/hive-operator condition met
> Error from server (NotFound): deployments.apps "hive-controllers" not found

### What this PR does / why we need it:
Aligning with [production Hive installation](https://dev.azure.com/msazure/AzureRedHatOpenShift/_git/ARO-Pipelines/pullrequest/9992450) by not waiting for the _hive-controllers_ deployment to be **Available** and the pod to be **Ready**.
It's the responsibility of the operator to manage its resources, and it is an overkill that even causes the Hive installation to fail on waiting. Rerun the script was succeeded

### Test plan for issue:
Not needed

### Is there any documentation that needs to be updated for this PR?
I don't think so.

### How do you know this will function as expected in production?

2024-08-08 14:06 UTC, razo7 commented
/azp run ci, e2e

2024-08-12 02:20 UTC, hawkowl requested changes
I don't think we want to remove it entirely, but increase it to some amount that Hive will _surely_ be operational by. If we do want to just trust in the operator, then we should instead put in some output of the script that indicates how to tell when Hive is operational and you can use it (e.g. "check readiness via kubectl x y z to monitor rollout").

2024-08-12 13:15 UTC, tsatam commented
These waits/timeouts were intentionally added in order to solve for issues we were facing when deploying Hive into ARO production clusters, where the deployment itself was "healthy" but the Hive operator was degraded due to various issues (namely missing OpenShift-specific CRDs in the AKS clusters we run Hive in). 

Without these checks, the script would exit "successfully" and thus our deployment would be marked as successful, despite Hive being degraded. 

That being said, I don't necessarily think we need to retain _this_ specific solution to that problem, and there's probably a better long-term solution (e.g. release pipeline takes Hive health metrics into account). 

For now I think we could make this change if truly desired, since this script isn't itself used for production Hive deployments. I just backported the changes we made to the production deployment script here.

2024-08-27 10:43 UTC, razo7 commented on hack/hive/hive-dev-install.sh
> +	rm -f /tmp/.tmp-secret
Not used in production, so it might be possible to remove it from here as well.

2024-08-27 12:06 UTC, razo7 commented
/azp run ci, e2e

2024-08-28 04:59 UTC, razo7 commented
/azp run e2e

2024-08-28 07:08 UTC, razo7 commented on hack/hive/hive-config/generate.go
> +//go:generate go run ../../genhiveconfig ./hive-additional-install-log-regexes.yaml
Probably moving the `genhiveconfig` directory under `hack/hive/` would be a good idea for grouping Azure resources.

2024-09-05 19:58 UTC, SudoBrendan requested changes

2024-09-05 19:58 UTC, SudoBrendan commented on hack/hive/hive-config/generate.go
flagging this as potentially needing a rebase on master to pick up the .bingo changes. Dismiss if untrue (but it probably doesn't hurt to do it anyways).

2024-09-08 06:54 UTC, razo7 commented on hack/hive/hive-config/generate.go
I believe you are referring to #3719. **Done**

2024-09-10 08:42 UTC, razo7 commented
/azp run ci, e2e

2024-09-11 10:21 UTC, razo7 commented
/azp run ci, e2e

2024-09-11 10:31 UTC, tiguelu commented
> I don't think we want to remove it entirely, but increase it to some amount that Hive will _surely_ be operational by. If we do want to just trust in the operator, then we should instead put in some output of the script that indicates how to tell when Hive is operational and you can use it (e.g. "check readiness via kubectl x y z to monitor rollout").

Thank you Amber. A log line has been added to print commands to check readiness.

2024-09-11 10:33 UTC, tiguelu approved these changes
All requested changes have been addressed. LGTM.

2024-09-11 12:31 UTC, merged