Check machine status and log details if it is not running
Azure/ARO-RP pull request #3887
Opened 2024-10-04 18:50 UTC by ventifus

### Which issue this PR addresses:

Provides more data for ARO-4247

### What this PR does / why we need it:

It is hard to troubleshoot worker node creation failures for new cluster installation. We wait for worker nodes, but sometimes they never show up because there was an Azure failure creating the VM. CAPI logs for machine creation happen too early and don't make it to Kusto.

### Test plan for issue:

Deploy test clusters and make sure we get the logs desired. Centraluseuap would be a good place to start if the error creating availability sets reproduces.

2024-10-04 18:55 UTC, tsatam approved these changes
LGTM (after fixing the pointer dereference in the log statement) - I think this functionality could do with some more robust unit tests but that can be a follow-up effort.

2024-10-04 19:26 UTC, tsatam commented
/azp run ci,e2e

2024-10-04 23:45 UTC, ventifus commented
/azp run ci,e2e

2024-10-07 16:53 UTC, ventifus commented
/azp run ci,e2e

2024-10-07 18:24 UTC, ventifus commented
/azp run ci,e2e

2024-10-09 18:30 UTC, shubhadapaithankar submitted a review, later dismissed

2024-10-09 20:05 UTC, kimorris27 requested changes
LGTM except for one spot where I think it's worth checking for nil pointers.

2024-10-09 20:05 UTC, kimorris27 commented on pkg/cluster/condition.go
> +		if *machine.Status.Phase == phaseRunning {
Nit: Let's check for nil pointers here just to be super safe.

2024-10-09 23:16 UTC, ventifus commented
/azp run ci,e2e

2024-10-10 14:10 UTC, kimorris27 approved these changes

2024-10-11 15:34 UTC, cadenmarchese approved these changes
lgtm

2024-10-14 17:40 UTC, merged