confirm UsesWorkloadIdentity shared utility function is used everywhere in ARO-RP
Azure/ARO-RP pull request #3932
Opened 2024-10-31 15:47 UTC by slawande2

### Which issue this PR addresses:
[ARO-11687](https://issues.redhat.com/browse/ARO-11687)

### What this PR does / why we need it:

### Test plan for issue:
Passed all unit tests

### Is there any documentation that needs to be updated for this PR?
N/A

2024-10-31 16:09 UTC, slawande2 commented
/azp run ci

2024-10-31 18:20 UTC, kimorris27 submitted a review, later dismissed

2024-10-31 18:20 UTC, kimorris27 commented
/azp run e2e

2024-11-01 18:20 UTC, cadenmarchese commented
/azp run e2e

2024-11-04 13:20 UTC, rajdeepc2792 commented on pkg/cluster/serviceprincipal.go
> +	if !m.doc.OpenShiftCluster.UsesWorkloadIdentity() {
This shouldn't be changed, this field is not related to MIWI cluster installation, I believe this function call will be handled for the MIWI flow as part of Update story.

2024-11-04 13:21 UTC, rajdeepc2792 requested changes
Requested a reversal of a change not related to MIWI.

2024-11-04 18:02 UTC, slawande2 commented
/azp run ci,e2e

2024-11-04 20:56 UTC, kimorris27 approved these changes

2024-11-05 20:05 UTC, cadenmarchese approved these changes

2024-11-08 17:19 UTC, merged