improve OCP version definition in local RP
Azure/ARO-RP pull request #4006
Opened 2024-12-12 16:32 UTC by Tof1973

### Which issue this PR addresses:

NA

### What this PR does / why we need it:

When creating local RP, it was not obvious to create the OCP release.
Also, for DEV we do not need to specify the sha for the image, and this eases the add of a release in the DB.

So I propose this PR.

### Test plan for issue:

NA

### Is there any documentation that needs to be updated for this PR?

NA

### How do you know this will function as expected in production? 

NA

2024-12-12 22:23 UTC, hlipsig requested changes
Just minor grammatical changes. Looks great thanks!

2024-12-12 22:23 UTC, hlipsig commented on docs/deploy-development-rp.md
> +      to `az aro create` with one of the version you added to your DB.
Nit: version -> versions

2024-12-12 22:23 UTC, hlipsig commented on docs/deploy-development-rp.md
> +This command adds the image to your cosmosDB. **openShiftPullspec** comes from [quay.io/repository/openshift-release-dev](https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags) (in pr
```suggestion
This command adds the image to your cosmosDB. **openShiftPullspec** comes from [quay.io/repository/openshift-release-dev](https://quay.io/repository/openshift-release-dev/ocp-release?tab=tags) (in production we must use sha tag, but in dev we can use tag for simplicity) ; and **installerPullspec** from int to work in dev without having to set any secret, but you can use repo for installer if you configured secret for it.
```

2024-12-12 22:23 UTC, hlipsig commented on docs/deploy-development-rp.md
> +      to `az aro create` with one of the version you added to your DB.
```suggestion
      to `az aro create` with one of the versions you added to your DB.
```

2024-12-13 13:59 UTC, Tof1973 commented
@hlipsig, should be OK now...

2025-01-08 02:55 UTC, hlipsig approved these changes

2025-01-08 02:56 UTC, hlipsig approved these changes

2025-01-08 02:57 UTC, merged