Incorporate ARM team feedback into v2024-08-12-preview API version
Azure/ARO-RP pull request #4014
Opened 2024-12-13 18:49 UTC by cadenmarchese

### Which issue this PR addresses:

Fixes

### What this PR does / why we need it:

### Test plan for issue:

### Is there any documentation that needs to be updated for this PR?

### How do you know this will function as expected in production?

2025-01-08 15:06 UTC, kimorris27 requested changes
I left a few small suggestions, but mostly LGTM.

2025-01-09 16:44 UTC, rajdeepc2792 commented on pkg/api/admin/platformworkloadidentityroleset_convert.go
> +		Type: s.Type,
As per the communication with @bennerv , it was decided to handle only `OpenShiftVersion ` that way since there would be old versions present in prod DB without name and type.
But that won't be the case with `platformworkloadidentityroleset` yet.

2025-01-09 16:45 UTC, rajdeepc2792 commented on pkg/api/v20240812preview/platformworkloadidentityroleset_convert.go
> +		Type: s.Type,
Same comment as above: https://github.com/Azure/ARO-RP/pull/4014#discussion_r1909146374

2025-01-09 18:55 UTC, kimorris27 commented on pkg/api/admin/platformworkloadidentityroleset_convert.go
> +		Type: s.Type,
Oh, makes sense 👍🏻

2025-01-09 20:36 UTC, rajdeepc2792 commented on pkg/swagger/swagger.go
> +		names = append(names, "OpenShiftVersion")
Moved it to the another block. No changes in the swagger though.

2025-01-09 21:43 UTC, kimorris27 commented on pkg/swagger/swagger.go
> +		names = append(names, "OpenShiftVersion")
Gotcha, I misunderstood then. I was thinking that the new singleton `GET` endpoint would only be added to the newest API version, but on a closer look at the code, it looks like we're supporting it for any API version that has an `OpenShiftVersionConverter`.

2025-01-09 21:44 UTC, kimorris27 approved these changes

2025-01-23 15:07 UTC, fahlmant approved these changes

2025-01-23 15:40 UTC, merged