Add PlatformWorkloadIdentityRoleSetsList to operations list for v2024-08-12-preview
Azure/ARO-RP pull request #4021
Opened 2024-12-18 13:52 UTC by cadenmarchese

### Which issue this PR addresses:

Fixes https://issues.redhat.com/browse/ARO-13257

### What this PR does / why we need it:

Adds missing PWIRS list to operations for the MIWI preview API.
### Test plan for issue:

CI and E2E

### Is there any documentation that needs to be updated for this PR?

### How do you know this will function as expected in production?

2024-12-18 16:56 UTC, fahlmant approved these changes

2024-12-18 19:54 UTC, tsatam requested changes

2024-12-18 19:54 UTC, tsatam commented on pkg/api/operation.go
> +	Name: "Microsoft.RedHatOpenShift/locations/listInstallVersions/read",
```suggestion
	Name: "Microsoft.RedHatOpenShift/locations/listPlatformWorkloadIdentityRoleSets/read",
```

2025-01-02 15:18 UTC, kimorris27 approved these changes

2025-01-02 19:25 UTC, tsatam approved these changes

2025-01-06 13:51 UTC, merged