Fix so that we mirror :latest
Azure/ARO-RP pull request #4029
Opened 2024-12-20 02:54 UTC by hawkowl

Make sure we mirror :latest so that images with shifting tags get updated correctly.

2024-12-23 14:29 UTC, cadenmarchese approved these changes

2025-01-02 16:15 UTC, kimorris27 approved these changes

2025-01-02 16:15 UTC, kimorris27 commented
/azp run ci

2025-01-02 16:17 UTC, kimorris27 requested changes
LGTM, but I think you'll need to reopen the PR using a branch off of the trunk repo so we can run CI.

2025-02-05 03:40 UTC, closed without merging