Migrate from subnet.Manager to use armnetwork.SubnetsClient
Azure/ARO-RP pull request #4033
Opened 2024-12-26 13:06 UTC by ehvs

### Which issue this PR addresses:
 Card https://issues.redhat.com/browse/ARO-12537 

### What this PR does / why we need it:

Migrates the outdated client Manager for the subnet to use armnetwork.

### Test plan for issue:

Unit tests and e2e

### Is there any documentation that needs to be updated for this PR?
No. Tech debt

2025-01-08 10:16 UTC, ehvs commented
@tiguelu @bitoku This change seems to impact the subnet_nsg.go and subnet_serviceendpoint.go as per messages from golint. Should I address those in the PR to comply?

2025-01-13 09:11 UTC, ehvs commented
CI failed, there are unit tests failing locally. WIP

2025-01-23 08:23 UTC, ehvs commented
Working on local PUCM tests.

2025-01-23 13:45 UTC, ehvs commented
/azp run ci

2025-02-11 16:57 UTC, ehvs commented
/azp run ci

2025-02-12 08:44 UTC, ehvs commented
Tested using local ARO operator, and it worked.

2025-02-17 08:44 UTC, tiguelu requested changes

2025-02-17 08:44 UTC, tiguelu commented on pkg/operator/controllers/subnets/subnet_controller_test.go
> +	"k8s.io/utils/ptr"
Can we use our own implementation of `ptr.To`? 

Reference: https://redhat-internal.slack.com/archives/C02ULBRS68M/p1731940533915429

2025-03-10 11:29 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_controller_test.go
> +	"k8s.io/utils/ptr"
Done.

2025-03-13 10:51 UTC, Tof1973 commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties.NetworkSecurityGroup != nil && strings.EqualFold(*subnetObject.Properties.NetworkSecurityGroup.ID, correctNSGResourceID) {
Wondering if we should not consider subnetObject.Properties.NetworkSecurityGroup.ID pointer nil to protect our code, even if that probably should not happen...

2025-03-25 14:25 UTC, bdematte commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties == nil {
I don't think this can happen without throwing an error (and then, exiting the function in the previous block).

2025-04-03 09:58 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties.NetworkSecurityGroup != nil && strings.EqualFold(*subnetObject.Properties.NetworkSecurityGroup.ID, correctNSGResourceID) {
Discussed it today in PR Review meeting, will look into implementing!

2025-04-03 10:58 UTC, ehvs commented on pkg/operator/controllers/subnets/subnets_controller.go
> +	subnetGroupsClient, err := armnetwork.NewSubnetsClient(resource.SubscriptionID, credential, options)
Good catch. This is a convention when using the  `armnetwork.<resource>GroupsClient`, for this case, would be sufficient to be `subnetClient` since there is no `subnetGroupsClient` : https://pkg.go.dev/github.com/Azure/ARO-RP/pkg/util/azureclient/azuresdk/armnetwork#NewSubnetsClient

2025-04-29 15:31 UTC, shubhadapaithankar commented on pkg/operator/controllers/subnets/subnet_serviceendpoint.go
> +			err = r.subnets.CreateOrUpdateAndWait(ctx, subnetID.ResourceGroupName, subnetID.Parent.Name, subnetID.Name, subnetObject.Subnet, nil)
Could we consider validating that subnetID.Parent.Name, subnetID.Name, and subnetID.ResourceGroupName are non-empty before invoking CreateOrUpdateAndWait? Just to avoid any unexpected ARM errors from malformed IDs.

2025-04-29 16:38 UTC, fahlmant commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties == nil {
Still good to double check IMO. That check helps explicitly avoid nil pointers

2025-06-19 12:33 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_serviceendpoint.go
> +		if r.subnets == nil { // just in case
The new client is not a pointer anymore. So in my recent change I completely deleted this line.

2025-06-19 12:34 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties == nil {
In further inspection, the nil validation is not actually validating if the subnet ID or name are empty. It will actually pass if any field inside subnetObject is filled. Eg: subnetObject.NetworkSecurityGroup.ID or subnetObject.ID or else. Which dismiss the point of a validation. So I am choosing to remove completely in favor of specific checks when needed.

2025-06-19 14:01 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_serviceendpoint.go
> +			err = r.subnets.CreateOrUpdateAndWait(ctx, subnetID.ResourceGroupName, subnetID.Parent.Name, subnetID.Name, subnetObject.Subnet, nil)
Hi @shubhadapaithankar , i was looking into this, and although we could add some manual validation for non-empty, taking a look on the whole repo does not seem a wide-adopted practice.
That said, it is a good point still.
Looking at the latest version of the `parseResourceID` which is the source from where these split fields come from, we could benefit from the latest error checks that were merged. I think that if we bump our own, we will have that nicely covered. https://github.com/Azure/azure-sdk-for-go/blob/10288adce4ede29da6301416454499a9fdad8db8/sdk/azcore/arm/internal/resource/resource_identifier.go#L64 
Opened a thread here too: https://redhat-internal.slack.com/archives/C02ULBRS68M/p1750341011301219

2025-06-20 13:34 UTC, tiguelu commented on pkg/operator/controllers/subnets/subnet_nsg.go
> +	if subnetObject.Properties == nil {
On closer look, Hevs showed me the new subnetObject is not a pointer any more, it only was in the old implementation. So we can resolve this thread.

2025-07-03 14:38 UTC, tiguelu commented
/azp run ci

2025-07-11 07:09 UTC, tiguelu commented on pkg/operator/controllers/subnets/subnet_controller_test.go
> +				mock.EXPECT().Get(gomock.Any(), vnetResourceGroup, vnetName, subnetObjectWorker, nil).Return(armnetwork.SubnetsClientGetResponse{Subnet: *subnetObjectWorker}, nil).MaxTimes(2)
```suggestion
				mock.EXPECT().Get(gomock.Any(), vnetResourceGroup, vnetName, subnetNameWorker, nil).Return(armnetwork.SubnetsClientGetResponse{Subnet: *subnetObjectWorker}, nil).MaxTimes(2)
```

Although it isn't making this test case to fail (because it's a disabled case maybe?), it looks like that param needs a change for the test to remain valid should anything else change in the future.

2025-07-11 15:31 UTC, ehvs commented on pkg/operator/controllers/subnets/subnet_controller_test.go
> +				mock.EXPECT().Get(gomock.Any(), vnetResourceGroup, vnetName, subnetObjectWorker, nil).Return(armnetwork.SubnetsClientGetResponse{Subnet: *subnetObjectWorker}, nil).MaxTimes(2)
Thanks for raising that. Will commit to update it.

2025-07-11 19:55 UTC, merged